//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCosmetic_app.ProductService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Product : ABCosmetic_app.ProductService.AbstractEntity {
        
        private decimal priceField;
        
        private int quantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        private int CategoryIDField;
        
        private int BrandIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ABCosmetic_app.ProductService.Product))]
    public partial class AbstractEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductService.ProductServiceSoap")]
    public interface ProductServiceSoap {
        
        // CODEGEN: Generating message contract since element name SearchProductsByPriceRangeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchProductsByPriceRange", ReplyAction="*")]
        ABCosmetic_app.ProductService.SearchProductsByPriceRangeResponse SearchProductsByPriceRange(ABCosmetic_app.ProductService.SearchProductsByPriceRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchProductsByPriceRange", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.ProductService.SearchProductsByPriceRangeResponse> SearchProductsByPriceRangeAsync(ABCosmetic_app.ProductService.SearchProductsByPriceRangeRequest request);
        
        // CODEGEN: Generating message contract since element name SearchProductsByPRCResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchProductsByPRC", ReplyAction="*")]
        ABCosmetic_app.ProductService.SearchProductsByPRCResponse SearchProductsByPRC(ABCosmetic_app.ProductService.SearchProductsByPRCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchProductsByPRC", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.ProductService.SearchProductsByPRCResponse> SearchProductsByPRCAsync(ABCosmetic_app.ProductService.SearchProductsByPRCRequest request);
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ABCosmetic_app.ProductService.HelloWorldResponse HelloWorld(ABCosmetic_app.ProductService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.ProductService.HelloWorldResponse> HelloWorldAsync(ABCosmetic_app.ProductService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name AllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/All", ReplyAction="*")]
        ABCosmetic_app.ProductService.AllResponse All(ABCosmetic_app.ProductService.AllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/All", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.ProductService.AllResponse> AllAsync(ABCosmetic_app.ProductService.AllRequest request);
        
        // CODEGEN: Generating message contract since element name GetByIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByID", ReplyAction="*")]
        ABCosmetic_app.ProductService.GetByIDResponse GetByID(ABCosmetic_app.ProductService.GetByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByID", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.ProductService.GetByIDResponse> GetByIDAsync(ABCosmetic_app.ProductService.GetByIDRequest request);
        
        // CODEGEN: Generating message contract since element name text from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchByName", ReplyAction="*")]
        ABCosmetic_app.ProductService.SearchByNameResponse SearchByName(ABCosmetic_app.ProductService.SearchByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchByName", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.ProductService.SearchByNameResponse> SearchByNameAsync(ABCosmetic_app.ProductService.SearchByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchProductsByPriceRangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchProductsByPriceRange", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.ProductService.SearchProductsByPriceRangeRequestBody Body;
        
        public SearchProductsByPriceRangeRequest() {
        }
        
        public SearchProductsByPriceRangeRequest(ABCosmetic_app.ProductService.SearchProductsByPriceRangeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchProductsByPriceRangeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal low;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal high;
        
        public SearchProductsByPriceRangeRequestBody() {
        }
        
        public SearchProductsByPriceRangeRequestBody(decimal low, decimal high) {
            this.low = low;
            this.high = high;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchProductsByPriceRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchProductsByPriceRangeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.ProductService.SearchProductsByPriceRangeResponseBody Body;
        
        public SearchProductsByPriceRangeResponse() {
        }
        
        public SearchProductsByPriceRangeResponse(ABCosmetic_app.ProductService.SearchProductsByPriceRangeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchProductsByPriceRangeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.ProductService.Product> SearchProductsByPriceRangeResult;
        
        public SearchProductsByPriceRangeResponseBody() {
        }
        
        public SearchProductsByPriceRangeResponseBody(System.Collections.Generic.List<ABCosmetic_app.ProductService.Product> SearchProductsByPriceRangeResult) {
            this.SearchProductsByPriceRangeResult = SearchProductsByPriceRangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchProductsByPRCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchProductsByPRC", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.ProductService.SearchProductsByPRCRequestBody Body;
        
        public SearchProductsByPRCRequest() {
        }
        
        public SearchProductsByPRCRequest(ABCosmetic_app.ProductService.SearchProductsByPRCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchProductsByPRCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal low;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal high;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cId;
        
        public SearchProductsByPRCRequestBody() {
        }
        
        public SearchProductsByPRCRequestBody(decimal low, decimal high, int cId) {
            this.low = low;
            this.high = high;
            this.cId = cId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchProductsByPRCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchProductsByPRCResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.ProductService.SearchProductsByPRCResponseBody Body;
        
        public SearchProductsByPRCResponse() {
        }
        
        public SearchProductsByPRCResponse(ABCosmetic_app.ProductService.SearchProductsByPRCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchProductsByPRCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.ProductService.Product> SearchProductsByPRCResult;
        
        public SearchProductsByPRCResponseBody() {
        }
        
        public SearchProductsByPRCResponseBody(System.Collections.Generic.List<ABCosmetic_app.ProductService.Product> SearchProductsByPRCResult) {
            this.SearchProductsByPRCResult = SearchProductsByPRCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.ProductService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ABCosmetic_app.ProductService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.ProductService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ABCosmetic_app.ProductService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="All", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.ProductService.AllRequestBody Body;
        
        public AllRequest() {
        }
        
        public AllRequest(ABCosmetic_app.ProductService.AllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllRequestBody {
        
        public AllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.ProductService.AllResponseBody Body;
        
        public AllResponse() {
        }
        
        public AllResponse(ABCosmetic_app.ProductService.AllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.ProductService.Product> AllResult;
        
        public AllResponseBody() {
        }
        
        public AllResponseBody(System.Collections.Generic.List<ABCosmetic_app.ProductService.Product> AllResult) {
            this.AllResult = AllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByID", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.ProductService.GetByIDRequestBody Body;
        
        public GetByIDRequest() {
        }
        
        public GetByIDRequest(ABCosmetic_app.ProductService.GetByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetByIDRequestBody() {
        }
        
        public GetByIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.ProductService.GetByIDResponseBody Body;
        
        public GetByIDResponse() {
        }
        
        public GetByIDResponse(ABCosmetic_app.ProductService.GetByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ABCosmetic_app.ProductService.Product GetByIDResult;
        
        public GetByIDResponseBody() {
        }
        
        public GetByIDResponseBody(ABCosmetic_app.ProductService.Product GetByIDResult) {
            this.GetByIDResult = GetByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByName", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.ProductService.SearchByNameRequestBody Body;
        
        public SearchByNameRequest() {
        }
        
        public SearchByNameRequest(ABCosmetic_app.ProductService.SearchByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        public SearchByNameRequestBody() {
        }
        
        public SearchByNameRequestBody(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.ProductService.SearchByNameResponseBody Body;
        
        public SearchByNameResponse() {
        }
        
        public SearchByNameResponse(ABCosmetic_app.ProductService.SearchByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.ProductService.Product> SearchByNameResult;
        
        public SearchByNameResponseBody() {
        }
        
        public SearchByNameResponseBody(System.Collections.Generic.List<ABCosmetic_app.ProductService.Product> SearchByNameResult) {
            this.SearchByNameResult = SearchByNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductServiceSoapChannel : ABCosmetic_app.ProductService.ProductServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceSoapClient : System.ServiceModel.ClientBase<ABCosmetic_app.ProductService.ProductServiceSoap>, ABCosmetic_app.ProductService.ProductServiceSoap {
        
        public ProductServiceSoapClient() {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.ProductService.SearchProductsByPriceRangeResponse ABCosmetic_app.ProductService.ProductServiceSoap.SearchProductsByPriceRange(ABCosmetic_app.ProductService.SearchProductsByPriceRangeRequest request) {
            return base.Channel.SearchProductsByPriceRange(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.ProductService.Product> SearchProductsByPriceRange(decimal low, decimal high) {
            ABCosmetic_app.ProductService.SearchProductsByPriceRangeRequest inValue = new ABCosmetic_app.ProductService.SearchProductsByPriceRangeRequest();
            inValue.Body = new ABCosmetic_app.ProductService.SearchProductsByPriceRangeRequestBody();
            inValue.Body.low = low;
            inValue.Body.high = high;
            ABCosmetic_app.ProductService.SearchProductsByPriceRangeResponse retVal = ((ABCosmetic_app.ProductService.ProductServiceSoap)(this)).SearchProductsByPriceRange(inValue);
            return retVal.Body.SearchProductsByPriceRangeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.ProductService.SearchProductsByPriceRangeResponse> ABCosmetic_app.ProductService.ProductServiceSoap.SearchProductsByPriceRangeAsync(ABCosmetic_app.ProductService.SearchProductsByPriceRangeRequest request) {
            return base.Channel.SearchProductsByPriceRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.ProductService.SearchProductsByPriceRangeResponse> SearchProductsByPriceRangeAsync(decimal low, decimal high) {
            ABCosmetic_app.ProductService.SearchProductsByPriceRangeRequest inValue = new ABCosmetic_app.ProductService.SearchProductsByPriceRangeRequest();
            inValue.Body = new ABCosmetic_app.ProductService.SearchProductsByPriceRangeRequestBody();
            inValue.Body.low = low;
            inValue.Body.high = high;
            return ((ABCosmetic_app.ProductService.ProductServiceSoap)(this)).SearchProductsByPriceRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.ProductService.SearchProductsByPRCResponse ABCosmetic_app.ProductService.ProductServiceSoap.SearchProductsByPRC(ABCosmetic_app.ProductService.SearchProductsByPRCRequest request) {
            return base.Channel.SearchProductsByPRC(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.ProductService.Product> SearchProductsByPRC(decimal low, decimal high, int cId) {
            ABCosmetic_app.ProductService.SearchProductsByPRCRequest inValue = new ABCosmetic_app.ProductService.SearchProductsByPRCRequest();
            inValue.Body = new ABCosmetic_app.ProductService.SearchProductsByPRCRequestBody();
            inValue.Body.low = low;
            inValue.Body.high = high;
            inValue.Body.cId = cId;
            ABCosmetic_app.ProductService.SearchProductsByPRCResponse retVal = ((ABCosmetic_app.ProductService.ProductServiceSoap)(this)).SearchProductsByPRC(inValue);
            return retVal.Body.SearchProductsByPRCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.ProductService.SearchProductsByPRCResponse> ABCosmetic_app.ProductService.ProductServiceSoap.SearchProductsByPRCAsync(ABCosmetic_app.ProductService.SearchProductsByPRCRequest request) {
            return base.Channel.SearchProductsByPRCAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.ProductService.SearchProductsByPRCResponse> SearchProductsByPRCAsync(decimal low, decimal high, int cId) {
            ABCosmetic_app.ProductService.SearchProductsByPRCRequest inValue = new ABCosmetic_app.ProductService.SearchProductsByPRCRequest();
            inValue.Body = new ABCosmetic_app.ProductService.SearchProductsByPRCRequestBody();
            inValue.Body.low = low;
            inValue.Body.high = high;
            inValue.Body.cId = cId;
            return ((ABCosmetic_app.ProductService.ProductServiceSoap)(this)).SearchProductsByPRCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.ProductService.HelloWorldResponse ABCosmetic_app.ProductService.ProductServiceSoap.HelloWorld(ABCosmetic_app.ProductService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ABCosmetic_app.ProductService.HelloWorldRequest inValue = new ABCosmetic_app.ProductService.HelloWorldRequest();
            inValue.Body = new ABCosmetic_app.ProductService.HelloWorldRequestBody();
            ABCosmetic_app.ProductService.HelloWorldResponse retVal = ((ABCosmetic_app.ProductService.ProductServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.ProductService.HelloWorldResponse> ABCosmetic_app.ProductService.ProductServiceSoap.HelloWorldAsync(ABCosmetic_app.ProductService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.ProductService.HelloWorldResponse> HelloWorldAsync() {
            ABCosmetic_app.ProductService.HelloWorldRequest inValue = new ABCosmetic_app.ProductService.HelloWorldRequest();
            inValue.Body = new ABCosmetic_app.ProductService.HelloWorldRequestBody();
            return ((ABCosmetic_app.ProductService.ProductServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.ProductService.AllResponse ABCosmetic_app.ProductService.ProductServiceSoap.All(ABCosmetic_app.ProductService.AllRequest request) {
            return base.Channel.All(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.ProductService.Product> All() {
            ABCosmetic_app.ProductService.AllRequest inValue = new ABCosmetic_app.ProductService.AllRequest();
            inValue.Body = new ABCosmetic_app.ProductService.AllRequestBody();
            ABCosmetic_app.ProductService.AllResponse retVal = ((ABCosmetic_app.ProductService.ProductServiceSoap)(this)).All(inValue);
            return retVal.Body.AllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.ProductService.AllResponse> ABCosmetic_app.ProductService.ProductServiceSoap.AllAsync(ABCosmetic_app.ProductService.AllRequest request) {
            return base.Channel.AllAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.ProductService.AllResponse> AllAsync() {
            ABCosmetic_app.ProductService.AllRequest inValue = new ABCosmetic_app.ProductService.AllRequest();
            inValue.Body = new ABCosmetic_app.ProductService.AllRequestBody();
            return ((ABCosmetic_app.ProductService.ProductServiceSoap)(this)).AllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.ProductService.GetByIDResponse ABCosmetic_app.ProductService.ProductServiceSoap.GetByID(ABCosmetic_app.ProductService.GetByIDRequest request) {
            return base.Channel.GetByID(request);
        }
        
        public ABCosmetic_app.ProductService.Product GetByID(int id) {
            ABCosmetic_app.ProductService.GetByIDRequest inValue = new ABCosmetic_app.ProductService.GetByIDRequest();
            inValue.Body = new ABCosmetic_app.ProductService.GetByIDRequestBody();
            inValue.Body.id = id;
            ABCosmetic_app.ProductService.GetByIDResponse retVal = ((ABCosmetic_app.ProductService.ProductServiceSoap)(this)).GetByID(inValue);
            return retVal.Body.GetByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.ProductService.GetByIDResponse> ABCosmetic_app.ProductService.ProductServiceSoap.GetByIDAsync(ABCosmetic_app.ProductService.GetByIDRequest request) {
            return base.Channel.GetByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.ProductService.GetByIDResponse> GetByIDAsync(int id) {
            ABCosmetic_app.ProductService.GetByIDRequest inValue = new ABCosmetic_app.ProductService.GetByIDRequest();
            inValue.Body = new ABCosmetic_app.ProductService.GetByIDRequestBody();
            inValue.Body.id = id;
            return ((ABCosmetic_app.ProductService.ProductServiceSoap)(this)).GetByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.ProductService.SearchByNameResponse ABCosmetic_app.ProductService.ProductServiceSoap.SearchByName(ABCosmetic_app.ProductService.SearchByNameRequest request) {
            return base.Channel.SearchByName(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.ProductService.Product> SearchByName(string text) {
            ABCosmetic_app.ProductService.SearchByNameRequest inValue = new ABCosmetic_app.ProductService.SearchByNameRequest();
            inValue.Body = new ABCosmetic_app.ProductService.SearchByNameRequestBody();
            inValue.Body.text = text;
            ABCosmetic_app.ProductService.SearchByNameResponse retVal = ((ABCosmetic_app.ProductService.ProductServiceSoap)(this)).SearchByName(inValue);
            return retVal.Body.SearchByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.ProductService.SearchByNameResponse> ABCosmetic_app.ProductService.ProductServiceSoap.SearchByNameAsync(ABCosmetic_app.ProductService.SearchByNameRequest request) {
            return base.Channel.SearchByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.ProductService.SearchByNameResponse> SearchByNameAsync(string text) {
            ABCosmetic_app.ProductService.SearchByNameRequest inValue = new ABCosmetic_app.ProductService.SearchByNameRequest();
            inValue.Body = new ABCosmetic_app.ProductService.SearchByNameRequestBody();
            inValue.Body.text = text;
            return ((ABCosmetic_app.ProductService.ProductServiceSoap)(this)).SearchByNameAsync(inValue);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
