//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCosmetic_app.OrderService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ABCosmetic_app.OrderService.Order))]
    public partial class AbstractEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Order : ABCosmetic_app.OrderService.AbstractEntity {
        
        private System.DateTime dateField;
        
        private decimal totalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        private int StatusIDField;
        
        private int CustomerIDField;
        
        private int StaffIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int StaffID {
            get {
                return this.StaffIDField;
            }
            set {
                if ((this.StaffIDField.Equals(value) != true)) {
                    this.StaffIDField = value;
                    this.RaisePropertyChanged("StaffID");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderService.OrderServiceSoap")]
    public interface OrderServiceSoap {
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNew", ReplyAction="*")]
        ABCosmetic_app.OrderService.AddNewResponse AddNew(ABCosmetic_app.OrderService.AddNewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNew", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.AddNewResponse> AddNewAsync(ABCosmetic_app.OrderService.AddNewRequest request);
        
        // CODEGEN: Generating message contract since element name GetOrdersByCustomerIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdersByCustomerID", ReplyAction="*")]
        ABCosmetic_app.OrderService.GetOrdersByCustomerIDResponse GetOrdersByCustomerID(ABCosmetic_app.OrderService.GetOrdersByCustomerIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdersByCustomerID", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetOrdersByCustomerIDResponse> GetOrdersByCustomerIDAsync(ABCosmetic_app.OrderService.GetOrdersByCustomerIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeOrderToPaied", ReplyAction="*")]
        bool ChangeOrderToPaied(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeOrderToPaied", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ChangeOrderToPaiedAsync(int id);
        
        // CODEGEN: Generating message contract since element name GetDailyOrdersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDailyOrders", ReplyAction="*")]
        ABCosmetic_app.OrderService.GetDailyOrdersResponse GetDailyOrders(ABCosmetic_app.OrderService.GetDailyOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDailyOrders", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetDailyOrdersResponse> GetDailyOrdersAsync(ABCosmetic_app.OrderService.GetDailyOrdersRequest request);
        
        // CODEGEN: Generating message contract since element name GetWeeklyOrdersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeeklyOrders", ReplyAction="*")]
        ABCosmetic_app.OrderService.GetWeeklyOrdersResponse GetWeeklyOrders(ABCosmetic_app.OrderService.GetWeeklyOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeeklyOrders", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetWeeklyOrdersResponse> GetWeeklyOrdersAsync(ABCosmetic_app.OrderService.GetWeeklyOrdersRequest request);
        
        // CODEGEN: Generating message contract since element name GetDailyOrdersForAStaffResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDailyOrdersForAStaff", ReplyAction="*")]
        ABCosmetic_app.OrderService.GetDailyOrdersForAStaffResponse GetDailyOrdersForAStaff(ABCosmetic_app.OrderService.GetDailyOrdersForAStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDailyOrdersForAStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetDailyOrdersForAStaffResponse> GetDailyOrdersForAStaffAsync(ABCosmetic_app.OrderService.GetDailyOrdersForAStaffRequest request);
        
        // CODEGEN: Generating message contract since element name GetWeeklyOrdersForAStaffResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeeklyOrdersForAStaff", ReplyAction="*")]
        ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffResponse GetWeeklyOrdersForAStaff(ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeeklyOrdersForAStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffResponse> GetWeeklyOrdersForAStaffAsync(ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffRequest request);
        
        // CODEGEN: Generating message contract since element name GetDailyOrdersForAStoreResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDailyOrdersForAStore", ReplyAction="*")]
        ABCosmetic_app.OrderService.GetDailyOrdersForAStoreResponse GetDailyOrdersForAStore(ABCosmetic_app.OrderService.GetDailyOrdersForAStoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDailyOrdersForAStore", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetDailyOrdersForAStoreResponse> GetDailyOrdersForAStoreAsync(ABCosmetic_app.OrderService.GetDailyOrdersForAStoreRequest request);
        
        // CODEGEN: Generating message contract since element name GetWeeklyOrdersForAStoreResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeeklyOrdersForAStore", ReplyAction="*")]
        ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreResponse GetWeeklyOrdersForAStore(ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeeklyOrdersForAStore", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreResponse> GetWeeklyOrdersForAStoreAsync(ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreRequest request);
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ABCosmetic_app.OrderService.HelloWorldResponse HelloWorld(ABCosmetic_app.OrderService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.HelloWorldResponse> HelloWorldAsync(ABCosmetic_app.OrderService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name AllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/All", ReplyAction="*")]
        ABCosmetic_app.OrderService.AllResponse All(ABCosmetic_app.OrderService.AllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/All", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.AllResponse> AllAsync(ABCosmetic_app.OrderService.AllRequest request);
        
        // CODEGEN: Generating message contract since element name GetByIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByID", ReplyAction="*")]
        ABCosmetic_app.OrderService.GetByIDResponse GetByID(ABCosmetic_app.OrderService.GetByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByID", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetByIDResponse> GetByIDAsync(ABCosmetic_app.OrderService.GetByIDRequest request);
        
        // CODEGEN: Generating message contract since element name text from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchByName", ReplyAction="*")]
        ABCosmetic_app.OrderService.SearchByNameResponse SearchByName(ABCosmetic_app.OrderService.SearchByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchByName", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.SearchByNameResponse> SearchByNameAsync(ABCosmetic_app.OrderService.SearchByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNew", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.AddNewRequestBody Body;
        
        public AddNewRequest() {
        }
        
        public AddNewRequest(ABCosmetic_app.OrderService.AddNewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int staffID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal total;
        
        public AddNewRequestBody() {
        }
        
        public AddNewRequestBody(string title, string content, int cId, int staffID, decimal total) {
            this.title = title;
            this.content = content;
            this.cId = cId;
            this.staffID = staffID;
            this.total = total;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.AddNewResponseBody Body;
        
        public AddNewResponse() {
        }
        
        public AddNewResponse(ABCosmetic_app.OrderService.AddNewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ABCosmetic_app.OrderService.Order AddNewResult;
        
        public AddNewResponseBody() {
        }
        
        public AddNewResponseBody(ABCosmetic_app.OrderService.Order AddNewResult) {
            this.AddNewResult = AddNewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersByCustomerIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersByCustomerID", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.GetOrdersByCustomerIDRequestBody Body;
        
        public GetOrdersByCustomerIDRequest() {
        }
        
        public GetOrdersByCustomerIDRequest(ABCosmetic_app.OrderService.GetOrdersByCustomerIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrdersByCustomerIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetOrdersByCustomerIDRequestBody() {
        }
        
        public GetOrdersByCustomerIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrdersByCustomerIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrdersByCustomerIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.GetOrdersByCustomerIDResponseBody Body;
        
        public GetOrdersByCustomerIDResponse() {
        }
        
        public GetOrdersByCustomerIDResponse(ABCosmetic_app.OrderService.GetOrdersByCustomerIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrdersByCustomerIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetOrdersByCustomerIDResult;
        
        public GetOrdersByCustomerIDResponseBody() {
        }
        
        public GetOrdersByCustomerIDResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetOrdersByCustomerIDResult) {
            this.GetOrdersByCustomerIDResult = GetOrdersByCustomerIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDailyOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDailyOrders", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.GetDailyOrdersRequestBody Body;
        
        public GetDailyOrdersRequest() {
        }
        
        public GetDailyOrdersRequest(ABCosmetic_app.OrderService.GetDailyOrdersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDailyOrdersRequestBody {
        
        public GetDailyOrdersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDailyOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDailyOrdersResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.GetDailyOrdersResponseBody Body;
        
        public GetDailyOrdersResponse() {
        }
        
        public GetDailyOrdersResponse(ABCosmetic_app.OrderService.GetDailyOrdersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDailyOrdersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetDailyOrdersResult;
        
        public GetDailyOrdersResponseBody() {
        }
        
        public GetDailyOrdersResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetDailyOrdersResult) {
            this.GetDailyOrdersResult = GetDailyOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeeklyOrdersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeeklyOrders", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.GetWeeklyOrdersRequestBody Body;
        
        public GetWeeklyOrdersRequest() {
        }
        
        public GetWeeklyOrdersRequest(ABCosmetic_app.OrderService.GetWeeklyOrdersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetWeeklyOrdersRequestBody {
        
        public GetWeeklyOrdersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeeklyOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeeklyOrdersResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.GetWeeklyOrdersResponseBody Body;
        
        public GetWeeklyOrdersResponse() {
        }
        
        public GetWeeklyOrdersResponse(ABCosmetic_app.OrderService.GetWeeklyOrdersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeeklyOrdersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetWeeklyOrdersResult;
        
        public GetWeeklyOrdersResponseBody() {
        }
        
        public GetWeeklyOrdersResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetWeeklyOrdersResult) {
            this.GetWeeklyOrdersResult = GetWeeklyOrdersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDailyOrdersForAStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDailyOrdersForAStaff", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.GetDailyOrdersForAStaffRequestBody Body;
        
        public GetDailyOrdersForAStaffRequest() {
        }
        
        public GetDailyOrdersForAStaffRequest(ABCosmetic_app.OrderService.GetDailyOrdersForAStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDailyOrdersForAStaffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int staffID;
        
        public GetDailyOrdersForAStaffRequestBody() {
        }
        
        public GetDailyOrdersForAStaffRequestBody(int staffID) {
            this.staffID = staffID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDailyOrdersForAStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDailyOrdersForAStaffResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.GetDailyOrdersForAStaffResponseBody Body;
        
        public GetDailyOrdersForAStaffResponse() {
        }
        
        public GetDailyOrdersForAStaffResponse(ABCosmetic_app.OrderService.GetDailyOrdersForAStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDailyOrdersForAStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetDailyOrdersForAStaffResult;
        
        public GetDailyOrdersForAStaffResponseBody() {
        }
        
        public GetDailyOrdersForAStaffResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetDailyOrdersForAStaffResult) {
            this.GetDailyOrdersForAStaffResult = GetDailyOrdersForAStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeeklyOrdersForAStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeeklyOrdersForAStaff", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffRequestBody Body;
        
        public GetWeeklyOrdersForAStaffRequest() {
        }
        
        public GetWeeklyOrdersForAStaffRequest(ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeeklyOrdersForAStaffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int staffID;
        
        public GetWeeklyOrdersForAStaffRequestBody() {
        }
        
        public GetWeeklyOrdersForAStaffRequestBody(int staffID) {
            this.staffID = staffID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeeklyOrdersForAStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeeklyOrdersForAStaffResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffResponseBody Body;
        
        public GetWeeklyOrdersForAStaffResponse() {
        }
        
        public GetWeeklyOrdersForAStaffResponse(ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeeklyOrdersForAStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetWeeklyOrdersForAStaffResult;
        
        public GetWeeklyOrdersForAStaffResponseBody() {
        }
        
        public GetWeeklyOrdersForAStaffResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetWeeklyOrdersForAStaffResult) {
            this.GetWeeklyOrdersForAStaffResult = GetWeeklyOrdersForAStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDailyOrdersForAStoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDailyOrdersForAStore", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.GetDailyOrdersForAStoreRequestBody Body;
        
        public GetDailyOrdersForAStoreRequest() {
        }
        
        public GetDailyOrdersForAStoreRequest(ABCosmetic_app.OrderService.GetDailyOrdersForAStoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDailyOrdersForAStoreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int storeID;
        
        public GetDailyOrdersForAStoreRequestBody() {
        }
        
        public GetDailyOrdersForAStoreRequestBody(int storeID) {
            this.storeID = storeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDailyOrdersForAStoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDailyOrdersForAStoreResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.GetDailyOrdersForAStoreResponseBody Body;
        
        public GetDailyOrdersForAStoreResponse() {
        }
        
        public GetDailyOrdersForAStoreResponse(ABCosmetic_app.OrderService.GetDailyOrdersForAStoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDailyOrdersForAStoreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetDailyOrdersForAStoreResult;
        
        public GetDailyOrdersForAStoreResponseBody() {
        }
        
        public GetDailyOrdersForAStoreResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetDailyOrdersForAStoreResult) {
            this.GetDailyOrdersForAStoreResult = GetDailyOrdersForAStoreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeeklyOrdersForAStoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeeklyOrdersForAStore", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreRequestBody Body;
        
        public GetWeeklyOrdersForAStoreRequest() {
        }
        
        public GetWeeklyOrdersForAStoreRequest(ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeeklyOrdersForAStoreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int storeID;
        
        public GetWeeklyOrdersForAStoreRequestBody() {
        }
        
        public GetWeeklyOrdersForAStoreRequestBody(int storeID) {
            this.storeID = storeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeeklyOrdersForAStoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeeklyOrdersForAStoreResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreResponseBody Body;
        
        public GetWeeklyOrdersForAStoreResponse() {
        }
        
        public GetWeeklyOrdersForAStoreResponse(ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeeklyOrdersForAStoreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetWeeklyOrdersForAStoreResult;
        
        public GetWeeklyOrdersForAStoreResponseBody() {
        }
        
        public GetWeeklyOrdersForAStoreResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetWeeklyOrdersForAStoreResult) {
            this.GetWeeklyOrdersForAStoreResult = GetWeeklyOrdersForAStoreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ABCosmetic_app.OrderService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ABCosmetic_app.OrderService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="All", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.AllRequestBody Body;
        
        public AllRequest() {
        }
        
        public AllRequest(ABCosmetic_app.OrderService.AllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllRequestBody {
        
        public AllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.AllResponseBody Body;
        
        public AllResponse() {
        }
        
        public AllResponse(ABCosmetic_app.OrderService.AllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> AllResult;
        
        public AllResponseBody() {
        }
        
        public AllResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> AllResult) {
            this.AllResult = AllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByID", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.GetByIDRequestBody Body;
        
        public GetByIDRequest() {
        }
        
        public GetByIDRequest(ABCosmetic_app.OrderService.GetByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetByIDRequestBody() {
        }
        
        public GetByIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.GetByIDResponseBody Body;
        
        public GetByIDResponse() {
        }
        
        public GetByIDResponse(ABCosmetic_app.OrderService.GetByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ABCosmetic_app.OrderService.Order GetByIDResult;
        
        public GetByIDResponseBody() {
        }
        
        public GetByIDResponseBody(ABCosmetic_app.OrderService.Order GetByIDResult) {
            this.GetByIDResult = GetByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByName", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.SearchByNameRequestBody Body;
        
        public SearchByNameRequest() {
        }
        
        public SearchByNameRequest(ABCosmetic_app.OrderService.SearchByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        public SearchByNameRequestBody() {
        }
        
        public SearchByNameRequestBody(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderService.SearchByNameResponseBody Body;
        
        public SearchByNameResponse() {
        }
        
        public SearchByNameResponse(ABCosmetic_app.OrderService.SearchByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> SearchByNameResult;
        
        public SearchByNameResponseBody() {
        }
        
        public SearchByNameResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> SearchByNameResult) {
            this.SearchByNameResult = SearchByNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderServiceSoapChannel : ABCosmetic_app.OrderService.OrderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceSoapClient : System.ServiceModel.ClientBase<ABCosmetic_app.OrderService.OrderServiceSoap>, ABCosmetic_app.OrderService.OrderServiceSoap {
        
        public OrderServiceSoapClient() {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderService.AddNewResponse ABCosmetic_app.OrderService.OrderServiceSoap.AddNew(ABCosmetic_app.OrderService.AddNewRequest request) {
            return base.Channel.AddNew(request);
        }
        
        public ABCosmetic_app.OrderService.Order AddNew(string title, string content, int cId, int staffID, decimal total) {
            ABCosmetic_app.OrderService.AddNewRequest inValue = new ABCosmetic_app.OrderService.AddNewRequest();
            inValue.Body = new ABCosmetic_app.OrderService.AddNewRequestBody();
            inValue.Body.title = title;
            inValue.Body.content = content;
            inValue.Body.cId = cId;
            inValue.Body.staffID = staffID;
            inValue.Body.total = total;
            ABCosmetic_app.OrderService.AddNewResponse retVal = ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).AddNew(inValue);
            return retVal.Body.AddNewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.AddNewResponse> ABCosmetic_app.OrderService.OrderServiceSoap.AddNewAsync(ABCosmetic_app.OrderService.AddNewRequest request) {
            return base.Channel.AddNewAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderService.AddNewResponse> AddNewAsync(string title, string content, int cId, int staffID, decimal total) {
            ABCosmetic_app.OrderService.AddNewRequest inValue = new ABCosmetic_app.OrderService.AddNewRequest();
            inValue.Body = new ABCosmetic_app.OrderService.AddNewRequestBody();
            inValue.Body.title = title;
            inValue.Body.content = content;
            inValue.Body.cId = cId;
            inValue.Body.staffID = staffID;
            inValue.Body.total = total;
            return ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).AddNewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderService.GetOrdersByCustomerIDResponse ABCosmetic_app.OrderService.OrderServiceSoap.GetOrdersByCustomerID(ABCosmetic_app.OrderService.GetOrdersByCustomerIDRequest request) {
            return base.Channel.GetOrdersByCustomerID(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetOrdersByCustomerID(int id) {
            ABCosmetic_app.OrderService.GetOrdersByCustomerIDRequest inValue = new ABCosmetic_app.OrderService.GetOrdersByCustomerIDRequest();
            inValue.Body = new ABCosmetic_app.OrderService.GetOrdersByCustomerIDRequestBody();
            inValue.Body.id = id;
            ABCosmetic_app.OrderService.GetOrdersByCustomerIDResponse retVal = ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).GetOrdersByCustomerID(inValue);
            return retVal.Body.GetOrdersByCustomerIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetOrdersByCustomerIDResponse> ABCosmetic_app.OrderService.OrderServiceSoap.GetOrdersByCustomerIDAsync(ABCosmetic_app.OrderService.GetOrdersByCustomerIDRequest request) {
            return base.Channel.GetOrdersByCustomerIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetOrdersByCustomerIDResponse> GetOrdersByCustomerIDAsync(int id) {
            ABCosmetic_app.OrderService.GetOrdersByCustomerIDRequest inValue = new ABCosmetic_app.OrderService.GetOrdersByCustomerIDRequest();
            inValue.Body = new ABCosmetic_app.OrderService.GetOrdersByCustomerIDRequestBody();
            inValue.Body.id = id;
            return ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).GetOrdersByCustomerIDAsync(inValue);
        }
        
        public bool ChangeOrderToPaied(int id) {
            return base.Channel.ChangeOrderToPaied(id);
        }
        
        public System.Threading.Tasks.Task<bool> ChangeOrderToPaiedAsync(int id) {
            return base.Channel.ChangeOrderToPaiedAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderService.GetDailyOrdersResponse ABCosmetic_app.OrderService.OrderServiceSoap.GetDailyOrders(ABCosmetic_app.OrderService.GetDailyOrdersRequest request) {
            return base.Channel.GetDailyOrders(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetDailyOrders() {
            ABCosmetic_app.OrderService.GetDailyOrdersRequest inValue = new ABCosmetic_app.OrderService.GetDailyOrdersRequest();
            inValue.Body = new ABCosmetic_app.OrderService.GetDailyOrdersRequestBody();
            ABCosmetic_app.OrderService.GetDailyOrdersResponse retVal = ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).GetDailyOrders(inValue);
            return retVal.Body.GetDailyOrdersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetDailyOrdersResponse> ABCosmetic_app.OrderService.OrderServiceSoap.GetDailyOrdersAsync(ABCosmetic_app.OrderService.GetDailyOrdersRequest request) {
            return base.Channel.GetDailyOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetDailyOrdersResponse> GetDailyOrdersAsync() {
            ABCosmetic_app.OrderService.GetDailyOrdersRequest inValue = new ABCosmetic_app.OrderService.GetDailyOrdersRequest();
            inValue.Body = new ABCosmetic_app.OrderService.GetDailyOrdersRequestBody();
            return ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).GetDailyOrdersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderService.GetWeeklyOrdersResponse ABCosmetic_app.OrderService.OrderServiceSoap.GetWeeklyOrders(ABCosmetic_app.OrderService.GetWeeklyOrdersRequest request) {
            return base.Channel.GetWeeklyOrders(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetWeeklyOrders() {
            ABCosmetic_app.OrderService.GetWeeklyOrdersRequest inValue = new ABCosmetic_app.OrderService.GetWeeklyOrdersRequest();
            inValue.Body = new ABCosmetic_app.OrderService.GetWeeklyOrdersRequestBody();
            ABCosmetic_app.OrderService.GetWeeklyOrdersResponse retVal = ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).GetWeeklyOrders(inValue);
            return retVal.Body.GetWeeklyOrdersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetWeeklyOrdersResponse> ABCosmetic_app.OrderService.OrderServiceSoap.GetWeeklyOrdersAsync(ABCosmetic_app.OrderService.GetWeeklyOrdersRequest request) {
            return base.Channel.GetWeeklyOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetWeeklyOrdersResponse> GetWeeklyOrdersAsync() {
            ABCosmetic_app.OrderService.GetWeeklyOrdersRequest inValue = new ABCosmetic_app.OrderService.GetWeeklyOrdersRequest();
            inValue.Body = new ABCosmetic_app.OrderService.GetWeeklyOrdersRequestBody();
            return ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).GetWeeklyOrdersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderService.GetDailyOrdersForAStaffResponse ABCosmetic_app.OrderService.OrderServiceSoap.GetDailyOrdersForAStaff(ABCosmetic_app.OrderService.GetDailyOrdersForAStaffRequest request) {
            return base.Channel.GetDailyOrdersForAStaff(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetDailyOrdersForAStaff(int staffID) {
            ABCosmetic_app.OrderService.GetDailyOrdersForAStaffRequest inValue = new ABCosmetic_app.OrderService.GetDailyOrdersForAStaffRequest();
            inValue.Body = new ABCosmetic_app.OrderService.GetDailyOrdersForAStaffRequestBody();
            inValue.Body.staffID = staffID;
            ABCosmetic_app.OrderService.GetDailyOrdersForAStaffResponse retVal = ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).GetDailyOrdersForAStaff(inValue);
            return retVal.Body.GetDailyOrdersForAStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetDailyOrdersForAStaffResponse> ABCosmetic_app.OrderService.OrderServiceSoap.GetDailyOrdersForAStaffAsync(ABCosmetic_app.OrderService.GetDailyOrdersForAStaffRequest request) {
            return base.Channel.GetDailyOrdersForAStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetDailyOrdersForAStaffResponse> GetDailyOrdersForAStaffAsync(int staffID) {
            ABCosmetic_app.OrderService.GetDailyOrdersForAStaffRequest inValue = new ABCosmetic_app.OrderService.GetDailyOrdersForAStaffRequest();
            inValue.Body = new ABCosmetic_app.OrderService.GetDailyOrdersForAStaffRequestBody();
            inValue.Body.staffID = staffID;
            return ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).GetDailyOrdersForAStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffResponse ABCosmetic_app.OrderService.OrderServiceSoap.GetWeeklyOrdersForAStaff(ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffRequest request) {
            return base.Channel.GetWeeklyOrdersForAStaff(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetWeeklyOrdersForAStaff(int staffID) {
            ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffRequest inValue = new ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffRequest();
            inValue.Body = new ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffRequestBody();
            inValue.Body.staffID = staffID;
            ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffResponse retVal = ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).GetWeeklyOrdersForAStaff(inValue);
            return retVal.Body.GetWeeklyOrdersForAStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffResponse> ABCosmetic_app.OrderService.OrderServiceSoap.GetWeeklyOrdersForAStaffAsync(ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffRequest request) {
            return base.Channel.GetWeeklyOrdersForAStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffResponse> GetWeeklyOrdersForAStaffAsync(int staffID) {
            ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffRequest inValue = new ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffRequest();
            inValue.Body = new ABCosmetic_app.OrderService.GetWeeklyOrdersForAStaffRequestBody();
            inValue.Body.staffID = staffID;
            return ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).GetWeeklyOrdersForAStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderService.GetDailyOrdersForAStoreResponse ABCosmetic_app.OrderService.OrderServiceSoap.GetDailyOrdersForAStore(ABCosmetic_app.OrderService.GetDailyOrdersForAStoreRequest request) {
            return base.Channel.GetDailyOrdersForAStore(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetDailyOrdersForAStore(int storeID) {
            ABCosmetic_app.OrderService.GetDailyOrdersForAStoreRequest inValue = new ABCosmetic_app.OrderService.GetDailyOrdersForAStoreRequest();
            inValue.Body = new ABCosmetic_app.OrderService.GetDailyOrdersForAStoreRequestBody();
            inValue.Body.storeID = storeID;
            ABCosmetic_app.OrderService.GetDailyOrdersForAStoreResponse retVal = ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).GetDailyOrdersForAStore(inValue);
            return retVal.Body.GetDailyOrdersForAStoreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetDailyOrdersForAStoreResponse> ABCosmetic_app.OrderService.OrderServiceSoap.GetDailyOrdersForAStoreAsync(ABCosmetic_app.OrderService.GetDailyOrdersForAStoreRequest request) {
            return base.Channel.GetDailyOrdersForAStoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetDailyOrdersForAStoreResponse> GetDailyOrdersForAStoreAsync(int storeID) {
            ABCosmetic_app.OrderService.GetDailyOrdersForAStoreRequest inValue = new ABCosmetic_app.OrderService.GetDailyOrdersForAStoreRequest();
            inValue.Body = new ABCosmetic_app.OrderService.GetDailyOrdersForAStoreRequestBody();
            inValue.Body.storeID = storeID;
            return ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).GetDailyOrdersForAStoreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreResponse ABCosmetic_app.OrderService.OrderServiceSoap.GetWeeklyOrdersForAStore(ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreRequest request) {
            return base.Channel.GetWeeklyOrdersForAStore(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> GetWeeklyOrdersForAStore(int storeID) {
            ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreRequest inValue = new ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreRequest();
            inValue.Body = new ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreRequestBody();
            inValue.Body.storeID = storeID;
            ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreResponse retVal = ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).GetWeeklyOrdersForAStore(inValue);
            return retVal.Body.GetWeeklyOrdersForAStoreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreResponse> ABCosmetic_app.OrderService.OrderServiceSoap.GetWeeklyOrdersForAStoreAsync(ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreRequest request) {
            return base.Channel.GetWeeklyOrdersForAStoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreResponse> GetWeeklyOrdersForAStoreAsync(int storeID) {
            ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreRequest inValue = new ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreRequest();
            inValue.Body = new ABCosmetic_app.OrderService.GetWeeklyOrdersForAStoreRequestBody();
            inValue.Body.storeID = storeID;
            return ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).GetWeeklyOrdersForAStoreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderService.HelloWorldResponse ABCosmetic_app.OrderService.OrderServiceSoap.HelloWorld(ABCosmetic_app.OrderService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ABCosmetic_app.OrderService.HelloWorldRequest inValue = new ABCosmetic_app.OrderService.HelloWorldRequest();
            inValue.Body = new ABCosmetic_app.OrderService.HelloWorldRequestBody();
            ABCosmetic_app.OrderService.HelloWorldResponse retVal = ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.HelloWorldResponse> ABCosmetic_app.OrderService.OrderServiceSoap.HelloWorldAsync(ABCosmetic_app.OrderService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderService.HelloWorldResponse> HelloWorldAsync() {
            ABCosmetic_app.OrderService.HelloWorldRequest inValue = new ABCosmetic_app.OrderService.HelloWorldRequest();
            inValue.Body = new ABCosmetic_app.OrderService.HelloWorldRequestBody();
            return ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderService.AllResponse ABCosmetic_app.OrderService.OrderServiceSoap.All(ABCosmetic_app.OrderService.AllRequest request) {
            return base.Channel.All(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> All() {
            ABCosmetic_app.OrderService.AllRequest inValue = new ABCosmetic_app.OrderService.AllRequest();
            inValue.Body = new ABCosmetic_app.OrderService.AllRequestBody();
            ABCosmetic_app.OrderService.AllResponse retVal = ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).All(inValue);
            return retVal.Body.AllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.AllResponse> ABCosmetic_app.OrderService.OrderServiceSoap.AllAsync(ABCosmetic_app.OrderService.AllRequest request) {
            return base.Channel.AllAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderService.AllResponse> AllAsync() {
            ABCosmetic_app.OrderService.AllRequest inValue = new ABCosmetic_app.OrderService.AllRequest();
            inValue.Body = new ABCosmetic_app.OrderService.AllRequestBody();
            return ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).AllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderService.GetByIDResponse ABCosmetic_app.OrderService.OrderServiceSoap.GetByID(ABCosmetic_app.OrderService.GetByIDRequest request) {
            return base.Channel.GetByID(request);
        }
        
        public ABCosmetic_app.OrderService.Order GetByID(int id) {
            ABCosmetic_app.OrderService.GetByIDRequest inValue = new ABCosmetic_app.OrderService.GetByIDRequest();
            inValue.Body = new ABCosmetic_app.OrderService.GetByIDRequestBody();
            inValue.Body.id = id;
            ABCosmetic_app.OrderService.GetByIDResponse retVal = ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).GetByID(inValue);
            return retVal.Body.GetByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetByIDResponse> ABCosmetic_app.OrderService.OrderServiceSoap.GetByIDAsync(ABCosmetic_app.OrderService.GetByIDRequest request) {
            return base.Channel.GetByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderService.GetByIDResponse> GetByIDAsync(int id) {
            ABCosmetic_app.OrderService.GetByIDRequest inValue = new ABCosmetic_app.OrderService.GetByIDRequest();
            inValue.Body = new ABCosmetic_app.OrderService.GetByIDRequestBody();
            inValue.Body.id = id;
            return ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).GetByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderService.SearchByNameResponse ABCosmetic_app.OrderService.OrderServiceSoap.SearchByName(ABCosmetic_app.OrderService.SearchByNameRequest request) {
            return base.Channel.SearchByName(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderService.Order> SearchByName(string text) {
            ABCosmetic_app.OrderService.SearchByNameRequest inValue = new ABCosmetic_app.OrderService.SearchByNameRequest();
            inValue.Body = new ABCosmetic_app.OrderService.SearchByNameRequestBody();
            inValue.Body.text = text;
            ABCosmetic_app.OrderService.SearchByNameResponse retVal = ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).SearchByName(inValue);
            return retVal.Body.SearchByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderService.SearchByNameResponse> ABCosmetic_app.OrderService.OrderServiceSoap.SearchByNameAsync(ABCosmetic_app.OrderService.SearchByNameRequest request) {
            return base.Channel.SearchByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderService.SearchByNameResponse> SearchByNameAsync(string text) {
            ABCosmetic_app.OrderService.SearchByNameRequest inValue = new ABCosmetic_app.OrderService.SearchByNameRequest();
            inValue.Body = new ABCosmetic_app.OrderService.SearchByNameRequestBody();
            inValue.Body.text = text;
            return ((ABCosmetic_app.OrderService.OrderServiceSoap)(this)).SearchByNameAsync(inValue);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
