//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCosmetic_app.CategoryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Category : ABCosmetic_app.CategoryService.AbstractEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ABCosmetic_app.CategoryService.Category))]
    public partial class AbstractEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CategoryService.CategoryServiceSoap")]
    public interface CategoryServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ABCosmetic_app.CategoryService.HelloWorldResponse HelloWorld(ABCosmetic_app.CategoryService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.CategoryService.HelloWorldResponse> HelloWorldAsync(ABCosmetic_app.CategoryService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name AllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/All", ReplyAction="*")]
        ABCosmetic_app.CategoryService.AllResponse All(ABCosmetic_app.CategoryService.AllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/All", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.CategoryService.AllResponse> AllAsync(ABCosmetic_app.CategoryService.AllRequest request);
        
        // CODEGEN: Generating message contract since element name GetByIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByID", ReplyAction="*")]
        ABCosmetic_app.CategoryService.GetByIDResponse GetByID(ABCosmetic_app.CategoryService.GetByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByID", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.CategoryService.GetByIDResponse> GetByIDAsync(ABCosmetic_app.CategoryService.GetByIDRequest request);
        
        // CODEGEN: Generating message contract since element name text from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchByName", ReplyAction="*")]
        ABCosmetic_app.CategoryService.SearchByNameResponse SearchByName(ABCosmetic_app.CategoryService.SearchByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchByName", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.CategoryService.SearchByNameResponse> SearchByNameAsync(ABCosmetic_app.CategoryService.SearchByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.CategoryService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ABCosmetic_app.CategoryService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.CategoryService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ABCosmetic_app.CategoryService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="All", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.CategoryService.AllRequestBody Body;
        
        public AllRequest() {
        }
        
        public AllRequest(ABCosmetic_app.CategoryService.AllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllRequestBody {
        
        public AllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.CategoryService.AllResponseBody Body;
        
        public AllResponse() {
        }
        
        public AllResponse(ABCosmetic_app.CategoryService.AllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.CategoryService.Category> AllResult;
        
        public AllResponseBody() {
        }
        
        public AllResponseBody(System.Collections.Generic.List<ABCosmetic_app.CategoryService.Category> AllResult) {
            this.AllResult = AllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByID", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.CategoryService.GetByIDRequestBody Body;
        
        public GetByIDRequest() {
        }
        
        public GetByIDRequest(ABCosmetic_app.CategoryService.GetByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetByIDRequestBody() {
        }
        
        public GetByIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.CategoryService.GetByIDResponseBody Body;
        
        public GetByIDResponse() {
        }
        
        public GetByIDResponse(ABCosmetic_app.CategoryService.GetByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ABCosmetic_app.CategoryService.Category GetByIDResult;
        
        public GetByIDResponseBody() {
        }
        
        public GetByIDResponseBody(ABCosmetic_app.CategoryService.Category GetByIDResult) {
            this.GetByIDResult = GetByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByName", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.CategoryService.SearchByNameRequestBody Body;
        
        public SearchByNameRequest() {
        }
        
        public SearchByNameRequest(ABCosmetic_app.CategoryService.SearchByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        public SearchByNameRequestBody() {
        }
        
        public SearchByNameRequestBody(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.CategoryService.SearchByNameResponseBody Body;
        
        public SearchByNameResponse() {
        }
        
        public SearchByNameResponse(ABCosmetic_app.CategoryService.SearchByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.CategoryService.Category> SearchByNameResult;
        
        public SearchByNameResponseBody() {
        }
        
        public SearchByNameResponseBody(System.Collections.Generic.List<ABCosmetic_app.CategoryService.Category> SearchByNameResult) {
            this.SearchByNameResult = SearchByNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CategoryServiceSoapChannel : ABCosmetic_app.CategoryService.CategoryServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoryServiceSoapClient : System.ServiceModel.ClientBase<ABCosmetic_app.CategoryService.CategoryServiceSoap>, ABCosmetic_app.CategoryService.CategoryServiceSoap {
        
        public CategoryServiceSoapClient() {
        }
        
        public CategoryServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoryServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.CategoryService.HelloWorldResponse ABCosmetic_app.CategoryService.CategoryServiceSoap.HelloWorld(ABCosmetic_app.CategoryService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ABCosmetic_app.CategoryService.HelloWorldRequest inValue = new ABCosmetic_app.CategoryService.HelloWorldRequest();
            inValue.Body = new ABCosmetic_app.CategoryService.HelloWorldRequestBody();
            ABCosmetic_app.CategoryService.HelloWorldResponse retVal = ((ABCosmetic_app.CategoryService.CategoryServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.CategoryService.HelloWorldResponse> ABCosmetic_app.CategoryService.CategoryServiceSoap.HelloWorldAsync(ABCosmetic_app.CategoryService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.CategoryService.HelloWorldResponse> HelloWorldAsync() {
            ABCosmetic_app.CategoryService.HelloWorldRequest inValue = new ABCosmetic_app.CategoryService.HelloWorldRequest();
            inValue.Body = new ABCosmetic_app.CategoryService.HelloWorldRequestBody();
            return ((ABCosmetic_app.CategoryService.CategoryServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.CategoryService.AllResponse ABCosmetic_app.CategoryService.CategoryServiceSoap.All(ABCosmetic_app.CategoryService.AllRequest request) {
            return base.Channel.All(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.CategoryService.Category> All() {
            ABCosmetic_app.CategoryService.AllRequest inValue = new ABCosmetic_app.CategoryService.AllRequest();
            inValue.Body = new ABCosmetic_app.CategoryService.AllRequestBody();
            ABCosmetic_app.CategoryService.AllResponse retVal = ((ABCosmetic_app.CategoryService.CategoryServiceSoap)(this)).All(inValue);
            return retVal.Body.AllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.CategoryService.AllResponse> ABCosmetic_app.CategoryService.CategoryServiceSoap.AllAsync(ABCosmetic_app.CategoryService.AllRequest request) {
            return base.Channel.AllAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.CategoryService.AllResponse> AllAsync() {
            ABCosmetic_app.CategoryService.AllRequest inValue = new ABCosmetic_app.CategoryService.AllRequest();
            inValue.Body = new ABCosmetic_app.CategoryService.AllRequestBody();
            return ((ABCosmetic_app.CategoryService.CategoryServiceSoap)(this)).AllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.CategoryService.GetByIDResponse ABCosmetic_app.CategoryService.CategoryServiceSoap.GetByID(ABCosmetic_app.CategoryService.GetByIDRequest request) {
            return base.Channel.GetByID(request);
        }
        
        public ABCosmetic_app.CategoryService.Category GetByID(int id) {
            ABCosmetic_app.CategoryService.GetByIDRequest inValue = new ABCosmetic_app.CategoryService.GetByIDRequest();
            inValue.Body = new ABCosmetic_app.CategoryService.GetByIDRequestBody();
            inValue.Body.id = id;
            ABCosmetic_app.CategoryService.GetByIDResponse retVal = ((ABCosmetic_app.CategoryService.CategoryServiceSoap)(this)).GetByID(inValue);
            return retVal.Body.GetByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.CategoryService.GetByIDResponse> ABCosmetic_app.CategoryService.CategoryServiceSoap.GetByIDAsync(ABCosmetic_app.CategoryService.GetByIDRequest request) {
            return base.Channel.GetByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.CategoryService.GetByIDResponse> GetByIDAsync(int id) {
            ABCosmetic_app.CategoryService.GetByIDRequest inValue = new ABCosmetic_app.CategoryService.GetByIDRequest();
            inValue.Body = new ABCosmetic_app.CategoryService.GetByIDRequestBody();
            inValue.Body.id = id;
            return ((ABCosmetic_app.CategoryService.CategoryServiceSoap)(this)).GetByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.CategoryService.SearchByNameResponse ABCosmetic_app.CategoryService.CategoryServiceSoap.SearchByName(ABCosmetic_app.CategoryService.SearchByNameRequest request) {
            return base.Channel.SearchByName(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.CategoryService.Category> SearchByName(string text) {
            ABCosmetic_app.CategoryService.SearchByNameRequest inValue = new ABCosmetic_app.CategoryService.SearchByNameRequest();
            inValue.Body = new ABCosmetic_app.CategoryService.SearchByNameRequestBody();
            inValue.Body.text = text;
            ABCosmetic_app.CategoryService.SearchByNameResponse retVal = ((ABCosmetic_app.CategoryService.CategoryServiceSoap)(this)).SearchByName(inValue);
            return retVal.Body.SearchByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.CategoryService.SearchByNameResponse> ABCosmetic_app.CategoryService.CategoryServiceSoap.SearchByNameAsync(ABCosmetic_app.CategoryService.SearchByNameRequest request) {
            return base.Channel.SearchByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.CategoryService.SearchByNameResponse> SearchByNameAsync(string text) {
            ABCosmetic_app.CategoryService.SearchByNameRequest inValue = new ABCosmetic_app.CategoryService.SearchByNameRequest();
            inValue.Body = new ABCosmetic_app.CategoryService.SearchByNameRequestBody();
            inValue.Body.text = text;
            return ((ABCosmetic_app.CategoryService.CategoryServiceSoap)(this)).SearchByNameAsync(inValue);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
