//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCosmetic_app.UserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ABCosmetic_app.UserService.User))]
    public partial class AbstractEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : ABCosmetic_app.UserService.AbstractEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string avatarField;
        
        private int RoleIDField;
        
        private System.Nullable<int> StoreIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string avatar {
            get {
                return this.avatarField;
            }
            set {
                if ((object.ReferenceEquals(this.avatarField, value) != true)) {
                    this.avatarField = value;
                    this.RaisePropertyChanged("avatar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((this.RoleIDField.Equals(value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> StoreID {
            get {
                return this.StoreIDField;
            }
            set {
                if ((this.StoreIDField.Equals(value) != true)) {
                    this.StoreIDField = value;
                    this.RaisePropertyChanged("StoreID");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.UserServiceSoap")]
    public interface UserServiceSoap {
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        ABCosmetic_app.UserService.LoginResponse Login(ABCosmetic_app.UserService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.LoginResponse> LoginAsync(ABCosmetic_app.UserService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsAdmin", ReplyAction="*")]
        ABCosmetic_app.UserService.IsAdminResponse IsAdmin(ABCosmetic_app.UserService.IsAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.IsAdminResponse> IsAdminAsync(ABCosmetic_app.UserService.IsAdminRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsStaff", ReplyAction="*")]
        ABCosmetic_app.UserService.IsStaffResponse IsStaff(ABCosmetic_app.UserService.IsStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.IsStaffResponse> IsStaffAsync(ABCosmetic_app.UserService.IsStaffRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsManager", ReplyAction="*")]
        ABCosmetic_app.UserService.IsManagerResponse IsManager(ABCosmetic_app.UserService.IsManagerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsManager", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.IsManagerResponse> IsManagerAsync(ABCosmetic_app.UserService.IsManagerRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserEmailResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserEmail", ReplyAction="*")]
        ABCosmetic_app.UserService.GetUserEmailResponse GetUserEmail(ABCosmetic_app.UserService.GetUserEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.GetUserEmailResponse> GetUserEmailAsync(ABCosmetic_app.UserService.GetUserEmailRequest request);
        
        // CODEGEN: Generating message contract since element name GetCustomersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomers", ReplyAction="*")]
        ABCosmetic_app.UserService.GetCustomersResponse GetCustomers(ABCosmetic_app.UserService.GetCustomersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomers", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.GetCustomersResponse> GetCustomersAsync(ABCosmetic_app.UserService.GetCustomersRequest request);
        
        // CODEGEN: Generating message contract since element name text from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchCustomersByName", ReplyAction="*")]
        ABCosmetic_app.UserService.SearchCustomersByNameResponse SearchCustomersByName(ABCosmetic_app.UserService.SearchCustomersByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchCustomersByName", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.SearchCustomersByNameResponse> SearchCustomersByNameAsync(ABCosmetic_app.UserService.SearchCustomersByNameRequest request);
        
        // CODEGEN: Generating message contract since element name GetStaffsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStaffs", ReplyAction="*")]
        ABCosmetic_app.UserService.GetStaffsResponse GetStaffs(ABCosmetic_app.UserService.GetStaffsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStaffs", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.GetStaffsResponse> GetStaffsAsync(ABCosmetic_app.UserService.GetStaffsRequest request);
        
        // CODEGEN: Generating message contract since element name text from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchStaffsByName", ReplyAction="*")]
        ABCosmetic_app.UserService.SearchStaffsByNameResponse SearchStaffsByName(ABCosmetic_app.UserService.SearchStaffsByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchStaffsByName", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.SearchStaffsByNameResponse> SearchStaffsByNameAsync(ABCosmetic_app.UserService.SearchStaffsByNameRequest request);
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ABCosmetic_app.UserService.HelloWorldResponse HelloWorld(ABCosmetic_app.UserService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.HelloWorldResponse> HelloWorldAsync(ABCosmetic_app.UserService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name AllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/All", ReplyAction="*")]
        ABCosmetic_app.UserService.AllResponse All(ABCosmetic_app.UserService.AllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/All", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.AllResponse> AllAsync(ABCosmetic_app.UserService.AllRequest request);
        
        // CODEGEN: Generating message contract since element name GetByIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByID", ReplyAction="*")]
        ABCosmetic_app.UserService.GetByIDResponse GetByID(ABCosmetic_app.UserService.GetByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByID", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.GetByIDResponse> GetByIDAsync(ABCosmetic_app.UserService.GetByIDRequest request);
        
        // CODEGEN: Generating message contract since element name text from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchByName", ReplyAction="*")]
        ABCosmetic_app.UserService.SearchByNameResponse SearchByName(ABCosmetic_app.UserService.SearchByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchByName", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.SearchByNameResponse> SearchByNameAsync(ABCosmetic_app.UserService.SearchByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ABCosmetic_app.UserService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ABCosmetic_app.UserService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ABCosmetic_app.UserService.User LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(ABCosmetic_app.UserService.User LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsAdmin", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.IsAdminRequestBody Body;
        
        public IsAdminRequest() {
        }
        
        public IsAdminRequest(ABCosmetic_app.UserService.IsAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public IsAdminRequestBody() {
        }
        
        public IsAdminRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsAdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.IsAdminResponseBody Body;
        
        public IsAdminResponse() {
        }
        
        public IsAdminResponse(ABCosmetic_app.UserService.IsAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsAdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsAdminResult;
        
        public IsAdminResponseBody() {
        }
        
        public IsAdminResponseBody(bool IsAdminResult) {
            this.IsAdminResult = IsAdminResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsStaff", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.IsStaffRequestBody Body;
        
        public IsStaffRequest() {
        }
        
        public IsStaffRequest(ABCosmetic_app.UserService.IsStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsStaffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public IsStaffRequestBody() {
        }
        
        public IsStaffRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsStaffResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.IsStaffResponseBody Body;
        
        public IsStaffResponse() {
        }
        
        public IsStaffResponse(ABCosmetic_app.UserService.IsStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsStaffResult;
        
        public IsStaffResponseBody() {
        }
        
        public IsStaffResponseBody(bool IsStaffResult) {
            this.IsStaffResult = IsStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsManagerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsManager", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.IsManagerRequestBody Body;
        
        public IsManagerRequest() {
        }
        
        public IsManagerRequest(ABCosmetic_app.UserService.IsManagerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsManagerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public IsManagerRequestBody() {
        }
        
        public IsManagerRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsManagerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsManagerResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.IsManagerResponseBody Body;
        
        public IsManagerResponse() {
        }
        
        public IsManagerResponse(ABCosmetic_app.UserService.IsManagerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsManagerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsManagerResult;
        
        public IsManagerResponseBody() {
        }
        
        public IsManagerResponseBody(bool IsManagerResult) {
            this.IsManagerResult = IsManagerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserEmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserEmail", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.GetUserEmailRequestBody Body;
        
        public GetUserEmailRequest() {
        }
        
        public GetUserEmailRequest(ABCosmetic_app.UserService.GetUserEmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserEmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetUserEmailRequestBody() {
        }
        
        public GetUserEmailRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserEmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserEmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.GetUserEmailResponseBody Body;
        
        public GetUserEmailResponse() {
        }
        
        public GetUserEmailResponse(ABCosmetic_app.UserService.GetUserEmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserEmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserEmailResult;
        
        public GetUserEmailResponseBody() {
        }
        
        public GetUserEmailResponseBody(string GetUserEmailResult) {
            this.GetUserEmailResult = GetUserEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomers", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.GetCustomersRequestBody Body;
        
        public GetCustomersRequest() {
        }
        
        public GetCustomersRequest(ABCosmetic_app.UserService.GetCustomersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCustomersRequestBody {
        
        public GetCustomersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomersResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.GetCustomersResponseBody Body;
        
        public GetCustomersResponse() {
        }
        
        public GetCustomersResponse(ABCosmetic_app.UserService.GetCustomersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.UserService.User> GetCustomersResult;
        
        public GetCustomersResponseBody() {
        }
        
        public GetCustomersResponseBody(System.Collections.Generic.List<ABCosmetic_app.UserService.User> GetCustomersResult) {
            this.GetCustomersResult = GetCustomersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchCustomersByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchCustomersByName", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.SearchCustomersByNameRequestBody Body;
        
        public SearchCustomersByNameRequest() {
        }
        
        public SearchCustomersByNameRequest(ABCosmetic_app.UserService.SearchCustomersByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchCustomersByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        public SearchCustomersByNameRequestBody() {
        }
        
        public SearchCustomersByNameRequestBody(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchCustomersByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchCustomersByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.SearchCustomersByNameResponseBody Body;
        
        public SearchCustomersByNameResponse() {
        }
        
        public SearchCustomersByNameResponse(ABCosmetic_app.UserService.SearchCustomersByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchCustomersByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.UserService.User> SearchCustomersByNameResult;
        
        public SearchCustomersByNameResponseBody() {
        }
        
        public SearchCustomersByNameResponseBody(System.Collections.Generic.List<ABCosmetic_app.UserService.User> SearchCustomersByNameResult) {
            this.SearchCustomersByNameResult = SearchCustomersByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStaffsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStaffs", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.GetStaffsRequestBody Body;
        
        public GetStaffsRequest() {
        }
        
        public GetStaffsRequest(ABCosmetic_app.UserService.GetStaffsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStaffsRequestBody {
        
        public GetStaffsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStaffsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStaffsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.GetStaffsResponseBody Body;
        
        public GetStaffsResponse() {
        }
        
        public GetStaffsResponse(ABCosmetic_app.UserService.GetStaffsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStaffsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.UserService.User> GetStaffsResult;
        
        public GetStaffsResponseBody() {
        }
        
        public GetStaffsResponseBody(System.Collections.Generic.List<ABCosmetic_app.UserService.User> GetStaffsResult) {
            this.GetStaffsResult = GetStaffsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchStaffsByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchStaffsByName", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.SearchStaffsByNameRequestBody Body;
        
        public SearchStaffsByNameRequest() {
        }
        
        public SearchStaffsByNameRequest(ABCosmetic_app.UserService.SearchStaffsByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchStaffsByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        public SearchStaffsByNameRequestBody() {
        }
        
        public SearchStaffsByNameRequestBody(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchStaffsByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchStaffsByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.SearchStaffsByNameResponseBody Body;
        
        public SearchStaffsByNameResponse() {
        }
        
        public SearchStaffsByNameResponse(ABCosmetic_app.UserService.SearchStaffsByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchStaffsByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.UserService.User> SearchStaffsByNameResult;
        
        public SearchStaffsByNameResponseBody() {
        }
        
        public SearchStaffsByNameResponseBody(System.Collections.Generic.List<ABCosmetic_app.UserService.User> SearchStaffsByNameResult) {
            this.SearchStaffsByNameResult = SearchStaffsByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ABCosmetic_app.UserService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ABCosmetic_app.UserService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="All", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.AllRequestBody Body;
        
        public AllRequest() {
        }
        
        public AllRequest(ABCosmetic_app.UserService.AllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllRequestBody {
        
        public AllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.AllResponseBody Body;
        
        public AllResponse() {
        }
        
        public AllResponse(ABCosmetic_app.UserService.AllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.UserService.User> AllResult;
        
        public AllResponseBody() {
        }
        
        public AllResponseBody(System.Collections.Generic.List<ABCosmetic_app.UserService.User> AllResult) {
            this.AllResult = AllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByID", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.GetByIDRequestBody Body;
        
        public GetByIDRequest() {
        }
        
        public GetByIDRequest(ABCosmetic_app.UserService.GetByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetByIDRequestBody() {
        }
        
        public GetByIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.GetByIDResponseBody Body;
        
        public GetByIDResponse() {
        }
        
        public GetByIDResponse(ABCosmetic_app.UserService.GetByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ABCosmetic_app.UserService.User GetByIDResult;
        
        public GetByIDResponseBody() {
        }
        
        public GetByIDResponseBody(ABCosmetic_app.UserService.User GetByIDResult) {
            this.GetByIDResult = GetByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByName", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.SearchByNameRequestBody Body;
        
        public SearchByNameRequest() {
        }
        
        public SearchByNameRequest(ABCosmetic_app.UserService.SearchByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        public SearchByNameRequestBody() {
        }
        
        public SearchByNameRequestBody(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.UserService.SearchByNameResponseBody Body;
        
        public SearchByNameResponse() {
        }
        
        public SearchByNameResponse(ABCosmetic_app.UserService.SearchByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.UserService.User> SearchByNameResult;
        
        public SearchByNameResponseBody() {
        }
        
        public SearchByNameResponseBody(System.Collections.Generic.List<ABCosmetic_app.UserService.User> SearchByNameResult) {
            this.SearchByNameResult = SearchByNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceSoapChannel : ABCosmetic_app.UserService.UserServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceSoapClient : System.ServiceModel.ClientBase<ABCosmetic_app.UserService.UserServiceSoap>, ABCosmetic_app.UserService.UserServiceSoap {
        
        public UserServiceSoapClient() {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.UserService.LoginResponse ABCosmetic_app.UserService.UserServiceSoap.Login(ABCosmetic_app.UserService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public ABCosmetic_app.UserService.User Login(string email, string password) {
            ABCosmetic_app.UserService.LoginRequest inValue = new ABCosmetic_app.UserService.LoginRequest();
            inValue.Body = new ABCosmetic_app.UserService.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            ABCosmetic_app.UserService.LoginResponse retVal = ((ABCosmetic_app.UserService.UserServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.LoginResponse> ABCosmetic_app.UserService.UserServiceSoap.LoginAsync(ABCosmetic_app.UserService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.UserService.LoginResponse> LoginAsync(string email, string password) {
            ABCosmetic_app.UserService.LoginRequest inValue = new ABCosmetic_app.UserService.LoginRequest();
            inValue.Body = new ABCosmetic_app.UserService.LoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((ABCosmetic_app.UserService.UserServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.UserService.IsAdminResponse ABCosmetic_app.UserService.UserServiceSoap.IsAdmin(ABCosmetic_app.UserService.IsAdminRequest request) {
            return base.Channel.IsAdmin(request);
        }
        
        public bool IsAdmin(string email) {
            ABCosmetic_app.UserService.IsAdminRequest inValue = new ABCosmetic_app.UserService.IsAdminRequest();
            inValue.Body = new ABCosmetic_app.UserService.IsAdminRequestBody();
            inValue.Body.email = email;
            ABCosmetic_app.UserService.IsAdminResponse retVal = ((ABCosmetic_app.UserService.UserServiceSoap)(this)).IsAdmin(inValue);
            return retVal.Body.IsAdminResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.IsAdminResponse> ABCosmetic_app.UserService.UserServiceSoap.IsAdminAsync(ABCosmetic_app.UserService.IsAdminRequest request) {
            return base.Channel.IsAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.UserService.IsAdminResponse> IsAdminAsync(string email) {
            ABCosmetic_app.UserService.IsAdminRequest inValue = new ABCosmetic_app.UserService.IsAdminRequest();
            inValue.Body = new ABCosmetic_app.UserService.IsAdminRequestBody();
            inValue.Body.email = email;
            return ((ABCosmetic_app.UserService.UserServiceSoap)(this)).IsAdminAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.UserService.IsStaffResponse ABCosmetic_app.UserService.UserServiceSoap.IsStaff(ABCosmetic_app.UserService.IsStaffRequest request) {
            return base.Channel.IsStaff(request);
        }
        
        public bool IsStaff(string email) {
            ABCosmetic_app.UserService.IsStaffRequest inValue = new ABCosmetic_app.UserService.IsStaffRequest();
            inValue.Body = new ABCosmetic_app.UserService.IsStaffRequestBody();
            inValue.Body.email = email;
            ABCosmetic_app.UserService.IsStaffResponse retVal = ((ABCosmetic_app.UserService.UserServiceSoap)(this)).IsStaff(inValue);
            return retVal.Body.IsStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.IsStaffResponse> ABCosmetic_app.UserService.UserServiceSoap.IsStaffAsync(ABCosmetic_app.UserService.IsStaffRequest request) {
            return base.Channel.IsStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.UserService.IsStaffResponse> IsStaffAsync(string email) {
            ABCosmetic_app.UserService.IsStaffRequest inValue = new ABCosmetic_app.UserService.IsStaffRequest();
            inValue.Body = new ABCosmetic_app.UserService.IsStaffRequestBody();
            inValue.Body.email = email;
            return ((ABCosmetic_app.UserService.UserServiceSoap)(this)).IsStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.UserService.IsManagerResponse ABCosmetic_app.UserService.UserServiceSoap.IsManager(ABCosmetic_app.UserService.IsManagerRequest request) {
            return base.Channel.IsManager(request);
        }
        
        public bool IsManager(string email) {
            ABCosmetic_app.UserService.IsManagerRequest inValue = new ABCosmetic_app.UserService.IsManagerRequest();
            inValue.Body = new ABCosmetic_app.UserService.IsManagerRequestBody();
            inValue.Body.email = email;
            ABCosmetic_app.UserService.IsManagerResponse retVal = ((ABCosmetic_app.UserService.UserServiceSoap)(this)).IsManager(inValue);
            return retVal.Body.IsManagerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.IsManagerResponse> ABCosmetic_app.UserService.UserServiceSoap.IsManagerAsync(ABCosmetic_app.UserService.IsManagerRequest request) {
            return base.Channel.IsManagerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.UserService.IsManagerResponse> IsManagerAsync(string email) {
            ABCosmetic_app.UserService.IsManagerRequest inValue = new ABCosmetic_app.UserService.IsManagerRequest();
            inValue.Body = new ABCosmetic_app.UserService.IsManagerRequestBody();
            inValue.Body.email = email;
            return ((ABCosmetic_app.UserService.UserServiceSoap)(this)).IsManagerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.UserService.GetUserEmailResponse ABCosmetic_app.UserService.UserServiceSoap.GetUserEmail(ABCosmetic_app.UserService.GetUserEmailRequest request) {
            return base.Channel.GetUserEmail(request);
        }
        
        public string GetUserEmail(int id) {
            ABCosmetic_app.UserService.GetUserEmailRequest inValue = new ABCosmetic_app.UserService.GetUserEmailRequest();
            inValue.Body = new ABCosmetic_app.UserService.GetUserEmailRequestBody();
            inValue.Body.id = id;
            ABCosmetic_app.UserService.GetUserEmailResponse retVal = ((ABCosmetic_app.UserService.UserServiceSoap)(this)).GetUserEmail(inValue);
            return retVal.Body.GetUserEmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.GetUserEmailResponse> ABCosmetic_app.UserService.UserServiceSoap.GetUserEmailAsync(ABCosmetic_app.UserService.GetUserEmailRequest request) {
            return base.Channel.GetUserEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.UserService.GetUserEmailResponse> GetUserEmailAsync(int id) {
            ABCosmetic_app.UserService.GetUserEmailRequest inValue = new ABCosmetic_app.UserService.GetUserEmailRequest();
            inValue.Body = new ABCosmetic_app.UserService.GetUserEmailRequestBody();
            inValue.Body.id = id;
            return ((ABCosmetic_app.UserService.UserServiceSoap)(this)).GetUserEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.UserService.GetCustomersResponse ABCosmetic_app.UserService.UserServiceSoap.GetCustomers(ABCosmetic_app.UserService.GetCustomersRequest request) {
            return base.Channel.GetCustomers(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.UserService.User> GetCustomers() {
            ABCosmetic_app.UserService.GetCustomersRequest inValue = new ABCosmetic_app.UserService.GetCustomersRequest();
            inValue.Body = new ABCosmetic_app.UserService.GetCustomersRequestBody();
            ABCosmetic_app.UserService.GetCustomersResponse retVal = ((ABCosmetic_app.UserService.UserServiceSoap)(this)).GetCustomers(inValue);
            return retVal.Body.GetCustomersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.GetCustomersResponse> ABCosmetic_app.UserService.UserServiceSoap.GetCustomersAsync(ABCosmetic_app.UserService.GetCustomersRequest request) {
            return base.Channel.GetCustomersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.UserService.GetCustomersResponse> GetCustomersAsync() {
            ABCosmetic_app.UserService.GetCustomersRequest inValue = new ABCosmetic_app.UserService.GetCustomersRequest();
            inValue.Body = new ABCosmetic_app.UserService.GetCustomersRequestBody();
            return ((ABCosmetic_app.UserService.UserServiceSoap)(this)).GetCustomersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.UserService.SearchCustomersByNameResponse ABCosmetic_app.UserService.UserServiceSoap.SearchCustomersByName(ABCosmetic_app.UserService.SearchCustomersByNameRequest request) {
            return base.Channel.SearchCustomersByName(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.UserService.User> SearchCustomersByName(string text) {
            ABCosmetic_app.UserService.SearchCustomersByNameRequest inValue = new ABCosmetic_app.UserService.SearchCustomersByNameRequest();
            inValue.Body = new ABCosmetic_app.UserService.SearchCustomersByNameRequestBody();
            inValue.Body.text = text;
            ABCosmetic_app.UserService.SearchCustomersByNameResponse retVal = ((ABCosmetic_app.UserService.UserServiceSoap)(this)).SearchCustomersByName(inValue);
            return retVal.Body.SearchCustomersByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.SearchCustomersByNameResponse> ABCosmetic_app.UserService.UserServiceSoap.SearchCustomersByNameAsync(ABCosmetic_app.UserService.SearchCustomersByNameRequest request) {
            return base.Channel.SearchCustomersByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.UserService.SearchCustomersByNameResponse> SearchCustomersByNameAsync(string text) {
            ABCosmetic_app.UserService.SearchCustomersByNameRequest inValue = new ABCosmetic_app.UserService.SearchCustomersByNameRequest();
            inValue.Body = new ABCosmetic_app.UserService.SearchCustomersByNameRequestBody();
            inValue.Body.text = text;
            return ((ABCosmetic_app.UserService.UserServiceSoap)(this)).SearchCustomersByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.UserService.GetStaffsResponse ABCosmetic_app.UserService.UserServiceSoap.GetStaffs(ABCosmetic_app.UserService.GetStaffsRequest request) {
            return base.Channel.GetStaffs(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.UserService.User> GetStaffs() {
            ABCosmetic_app.UserService.GetStaffsRequest inValue = new ABCosmetic_app.UserService.GetStaffsRequest();
            inValue.Body = new ABCosmetic_app.UserService.GetStaffsRequestBody();
            ABCosmetic_app.UserService.GetStaffsResponse retVal = ((ABCosmetic_app.UserService.UserServiceSoap)(this)).GetStaffs(inValue);
            return retVal.Body.GetStaffsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.GetStaffsResponse> ABCosmetic_app.UserService.UserServiceSoap.GetStaffsAsync(ABCosmetic_app.UserService.GetStaffsRequest request) {
            return base.Channel.GetStaffsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.UserService.GetStaffsResponse> GetStaffsAsync() {
            ABCosmetic_app.UserService.GetStaffsRequest inValue = new ABCosmetic_app.UserService.GetStaffsRequest();
            inValue.Body = new ABCosmetic_app.UserService.GetStaffsRequestBody();
            return ((ABCosmetic_app.UserService.UserServiceSoap)(this)).GetStaffsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.UserService.SearchStaffsByNameResponse ABCosmetic_app.UserService.UserServiceSoap.SearchStaffsByName(ABCosmetic_app.UserService.SearchStaffsByNameRequest request) {
            return base.Channel.SearchStaffsByName(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.UserService.User> SearchStaffsByName(string text) {
            ABCosmetic_app.UserService.SearchStaffsByNameRequest inValue = new ABCosmetic_app.UserService.SearchStaffsByNameRequest();
            inValue.Body = new ABCosmetic_app.UserService.SearchStaffsByNameRequestBody();
            inValue.Body.text = text;
            ABCosmetic_app.UserService.SearchStaffsByNameResponse retVal = ((ABCosmetic_app.UserService.UserServiceSoap)(this)).SearchStaffsByName(inValue);
            return retVal.Body.SearchStaffsByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.SearchStaffsByNameResponse> ABCosmetic_app.UserService.UserServiceSoap.SearchStaffsByNameAsync(ABCosmetic_app.UserService.SearchStaffsByNameRequest request) {
            return base.Channel.SearchStaffsByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.UserService.SearchStaffsByNameResponse> SearchStaffsByNameAsync(string text) {
            ABCosmetic_app.UserService.SearchStaffsByNameRequest inValue = new ABCosmetic_app.UserService.SearchStaffsByNameRequest();
            inValue.Body = new ABCosmetic_app.UserService.SearchStaffsByNameRequestBody();
            inValue.Body.text = text;
            return ((ABCosmetic_app.UserService.UserServiceSoap)(this)).SearchStaffsByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.UserService.HelloWorldResponse ABCosmetic_app.UserService.UserServiceSoap.HelloWorld(ABCosmetic_app.UserService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ABCosmetic_app.UserService.HelloWorldRequest inValue = new ABCosmetic_app.UserService.HelloWorldRequest();
            inValue.Body = new ABCosmetic_app.UserService.HelloWorldRequestBody();
            ABCosmetic_app.UserService.HelloWorldResponse retVal = ((ABCosmetic_app.UserService.UserServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.HelloWorldResponse> ABCosmetic_app.UserService.UserServiceSoap.HelloWorldAsync(ABCosmetic_app.UserService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.UserService.HelloWorldResponse> HelloWorldAsync() {
            ABCosmetic_app.UserService.HelloWorldRequest inValue = new ABCosmetic_app.UserService.HelloWorldRequest();
            inValue.Body = new ABCosmetic_app.UserService.HelloWorldRequestBody();
            return ((ABCosmetic_app.UserService.UserServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.UserService.AllResponse ABCosmetic_app.UserService.UserServiceSoap.All(ABCosmetic_app.UserService.AllRequest request) {
            return base.Channel.All(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.UserService.User> All() {
            ABCosmetic_app.UserService.AllRequest inValue = new ABCosmetic_app.UserService.AllRequest();
            inValue.Body = new ABCosmetic_app.UserService.AllRequestBody();
            ABCosmetic_app.UserService.AllResponse retVal = ((ABCosmetic_app.UserService.UserServiceSoap)(this)).All(inValue);
            return retVal.Body.AllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.AllResponse> ABCosmetic_app.UserService.UserServiceSoap.AllAsync(ABCosmetic_app.UserService.AllRequest request) {
            return base.Channel.AllAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.UserService.AllResponse> AllAsync() {
            ABCosmetic_app.UserService.AllRequest inValue = new ABCosmetic_app.UserService.AllRequest();
            inValue.Body = new ABCosmetic_app.UserService.AllRequestBody();
            return ((ABCosmetic_app.UserService.UserServiceSoap)(this)).AllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.UserService.GetByIDResponse ABCosmetic_app.UserService.UserServiceSoap.GetByID(ABCosmetic_app.UserService.GetByIDRequest request) {
            return base.Channel.GetByID(request);
        }
        
        public ABCosmetic_app.UserService.User GetByID(int id) {
            ABCosmetic_app.UserService.GetByIDRequest inValue = new ABCosmetic_app.UserService.GetByIDRequest();
            inValue.Body = new ABCosmetic_app.UserService.GetByIDRequestBody();
            inValue.Body.id = id;
            ABCosmetic_app.UserService.GetByIDResponse retVal = ((ABCosmetic_app.UserService.UserServiceSoap)(this)).GetByID(inValue);
            return retVal.Body.GetByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.GetByIDResponse> ABCosmetic_app.UserService.UserServiceSoap.GetByIDAsync(ABCosmetic_app.UserService.GetByIDRequest request) {
            return base.Channel.GetByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.UserService.GetByIDResponse> GetByIDAsync(int id) {
            ABCosmetic_app.UserService.GetByIDRequest inValue = new ABCosmetic_app.UserService.GetByIDRequest();
            inValue.Body = new ABCosmetic_app.UserService.GetByIDRequestBody();
            inValue.Body.id = id;
            return ((ABCosmetic_app.UserService.UserServiceSoap)(this)).GetByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.UserService.SearchByNameResponse ABCosmetic_app.UserService.UserServiceSoap.SearchByName(ABCosmetic_app.UserService.SearchByNameRequest request) {
            return base.Channel.SearchByName(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.UserService.User> SearchByName(string text) {
            ABCosmetic_app.UserService.SearchByNameRequest inValue = new ABCosmetic_app.UserService.SearchByNameRequest();
            inValue.Body = new ABCosmetic_app.UserService.SearchByNameRequestBody();
            inValue.Body.text = text;
            ABCosmetic_app.UserService.SearchByNameResponse retVal = ((ABCosmetic_app.UserService.UserServiceSoap)(this)).SearchByName(inValue);
            return retVal.Body.SearchByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.UserService.SearchByNameResponse> ABCosmetic_app.UserService.UserServiceSoap.SearchByNameAsync(ABCosmetic_app.UserService.SearchByNameRequest request) {
            return base.Channel.SearchByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.UserService.SearchByNameResponse> SearchByNameAsync(string text) {
            ABCosmetic_app.UserService.SearchByNameRequest inValue = new ABCosmetic_app.UserService.SearchByNameRequest();
            inValue.Body = new ABCosmetic_app.UserService.SearchByNameRequestBody();
            inValue.Body.text = text;
            return ((ABCosmetic_app.UserService.UserServiceSoap)(this)).SearchByNameAsync(inValue);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
