//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCosmetic_app.OrderDetailService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ABCosmetic_app.OrderDetailService.OrderDetail))]
    public partial class AbstractEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetail", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderDetail : ABCosmetic_app.OrderDetailService.AbstractEntity {
        
        private int quantityField;
        
        private int ProductIDField;
        
        private int OrderIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderDetailService.OrderDetailServiceSoap")]
    public interface OrderDetailServiceSoap {
        
        // CODEGEN: Generating message contract since element name AddNewResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNew", ReplyAction="*")]
        ABCosmetic_app.OrderDetailService.AddNewResponse AddNew(ABCosmetic_app.OrderDetailService.AddNewRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNew", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.AddNewResponse> AddNewAsync(ABCosmetic_app.OrderDetailService.AddNewRequest request);
        
        // CODEGEN: Generating message contract since element name GetDetailsByOrderIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDetailsByOrderID", ReplyAction="*")]
        ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDResponse GetDetailsByOrderID(ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDetailsByOrderID", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDResponse> GetDetailsByOrderIDAsync(ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDRequest request);
        
        // CODEGEN: Generating message contract since element name GetDailyDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDailyDetails", ReplyAction="*")]
        ABCosmetic_app.OrderDetailService.GetDailyDetailsResponse GetDailyDetails(ABCosmetic_app.OrderDetailService.GetDailyDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDailyDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetDailyDetailsResponse> GetDailyDetailsAsync(ABCosmetic_app.OrderDetailService.GetDailyDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name GetWeeklyDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeeklyDetails", ReplyAction="*")]
        ABCosmetic_app.OrderDetailService.GetWeeklyDetailsResponse GetWeeklyDetails(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeeklyDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetWeeklyDetailsResponse> GetWeeklyDetailsAsync(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name GetDailyDetailsForAStaffResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDailyDetailsForAStaff", ReplyAction="*")]
        ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffResponse GetDailyDetailsForAStaff(ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDailyDetailsForAStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffResponse> GetDailyDetailsForAStaffAsync(ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffRequest request);
        
        // CODEGEN: Generating message contract since element name GetWeeklyDetailsForAStaffResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeeklyDetailsForAStaff", ReplyAction="*")]
        ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffResponse GetWeeklyDetailsForAStaff(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeeklyDetailsForAStaff", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffResponse> GetWeeklyDetailsForAStaffAsync(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffRequest request);
        
        // CODEGEN: Generating message contract since element name GetDailyDetailsForAStoreResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDailyDetailsForAStore", ReplyAction="*")]
        ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreResponse GetDailyDetailsForAStore(ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDailyDetailsForAStore", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreResponse> GetDailyDetailsForAStoreAsync(ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreRequest request);
        
        // CODEGEN: Generating message contract since element name GetWeeklyDetailsForAStoreResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeeklyDetailsForAStore", ReplyAction="*")]
        ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreResponse GetWeeklyDetailsForAStore(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWeeklyDetailsForAStore", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreResponse> GetWeeklyDetailsForAStoreAsync(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreRequest request);
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ABCosmetic_app.OrderDetailService.HelloWorldResponse HelloWorld(ABCosmetic_app.OrderDetailService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.HelloWorldResponse> HelloWorldAsync(ABCosmetic_app.OrderDetailService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name AllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/All", ReplyAction="*")]
        ABCosmetic_app.OrderDetailService.AllResponse All(ABCosmetic_app.OrderDetailService.AllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/All", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.AllResponse> AllAsync(ABCosmetic_app.OrderDetailService.AllRequest request);
        
        // CODEGEN: Generating message contract since element name GetByIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByID", ReplyAction="*")]
        ABCosmetic_app.OrderDetailService.GetByIDResponse GetByID(ABCosmetic_app.OrderDetailService.GetByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByID", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetByIDResponse> GetByIDAsync(ABCosmetic_app.OrderDetailService.GetByIDRequest request);
        
        // CODEGEN: Generating message contract since element name text from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchByName", ReplyAction="*")]
        ABCosmetic_app.OrderDetailService.SearchByNameResponse SearchByName(ABCosmetic_app.OrderDetailService.SearchByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchByName", ReplyAction="*")]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.SearchByNameResponse> SearchByNameAsync(ABCosmetic_app.OrderDetailService.SearchByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNew", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.AddNewRequestBody Body;
        
        public AddNewRequest() {
        }
        
        public AddNewRequest(ABCosmetic_app.OrderDetailService.AddNewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int productID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int quantity;
        
        public AddNewRequestBody() {
        }
        
        public AddNewRequestBody(int orderID, int productID, int quantity) {
            this.orderID = orderID;
            this.productID = productID;
            this.quantity = quantity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.AddNewResponseBody Body;
        
        public AddNewResponse() {
        }
        
        public AddNewResponse(ABCosmetic_app.OrderDetailService.AddNewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ABCosmetic_app.OrderDetailService.OrderDetail AddNewResult;
        
        public AddNewResponseBody() {
        }
        
        public AddNewResponseBody(ABCosmetic_app.OrderDetailService.OrderDetail AddNewResult) {
            this.AddNewResult = AddNewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDetailsByOrderIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDetailsByOrderID", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDRequestBody Body;
        
        public GetDetailsByOrderIDRequest() {
        }
        
        public GetDetailsByOrderIDRequest(ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDetailsByOrderIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetDetailsByOrderIDRequestBody() {
        }
        
        public GetDetailsByOrderIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDetailsByOrderIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDetailsByOrderIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDResponseBody Body;
        
        public GetDetailsByOrderIDResponse() {
        }
        
        public GetDetailsByOrderIDResponse(ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDetailsByOrderIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetDetailsByOrderIDResult;
        
        public GetDetailsByOrderIDResponseBody() {
        }
        
        public GetDetailsByOrderIDResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetDetailsByOrderIDResult) {
            this.GetDetailsByOrderIDResult = GetDetailsByOrderIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDailyDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDailyDetails", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.GetDailyDetailsRequestBody Body;
        
        public GetDailyDetailsRequest() {
        }
        
        public GetDailyDetailsRequest(ABCosmetic_app.OrderDetailService.GetDailyDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDailyDetailsRequestBody {
        
        public GetDailyDetailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDailyDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDailyDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.GetDailyDetailsResponseBody Body;
        
        public GetDailyDetailsResponse() {
        }
        
        public GetDailyDetailsResponse(ABCosmetic_app.OrderDetailService.GetDailyDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDailyDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetDailyDetailsResult;
        
        public GetDailyDetailsResponseBody() {
        }
        
        public GetDailyDetailsResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetDailyDetailsResult) {
            this.GetDailyDetailsResult = GetDailyDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeeklyDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeeklyDetails", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.GetWeeklyDetailsRequestBody Body;
        
        public GetWeeklyDetailsRequest() {
        }
        
        public GetWeeklyDetailsRequest(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetWeeklyDetailsRequestBody {
        
        public GetWeeklyDetailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeeklyDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeeklyDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.GetWeeklyDetailsResponseBody Body;
        
        public GetWeeklyDetailsResponse() {
        }
        
        public GetWeeklyDetailsResponse(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeeklyDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetWeeklyDetailsResult;
        
        public GetWeeklyDetailsResponseBody() {
        }
        
        public GetWeeklyDetailsResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetWeeklyDetailsResult) {
            this.GetWeeklyDetailsResult = GetWeeklyDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDailyDetailsForAStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDailyDetailsForAStaff", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffRequestBody Body;
        
        public GetDailyDetailsForAStaffRequest() {
        }
        
        public GetDailyDetailsForAStaffRequest(ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDailyDetailsForAStaffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int staffID;
        
        public GetDailyDetailsForAStaffRequestBody() {
        }
        
        public GetDailyDetailsForAStaffRequestBody(int staffID) {
            this.staffID = staffID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDailyDetailsForAStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDailyDetailsForAStaffResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffResponseBody Body;
        
        public GetDailyDetailsForAStaffResponse() {
        }
        
        public GetDailyDetailsForAStaffResponse(ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDailyDetailsForAStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetDailyDetailsForAStaffResult;
        
        public GetDailyDetailsForAStaffResponseBody() {
        }
        
        public GetDailyDetailsForAStaffResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetDailyDetailsForAStaffResult) {
            this.GetDailyDetailsForAStaffResult = GetDailyDetailsForAStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeeklyDetailsForAStaffRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeeklyDetailsForAStaff", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffRequestBody Body;
        
        public GetWeeklyDetailsForAStaffRequest() {
        }
        
        public GetWeeklyDetailsForAStaffRequest(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeeklyDetailsForAStaffRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int staffID;
        
        public GetWeeklyDetailsForAStaffRequestBody() {
        }
        
        public GetWeeklyDetailsForAStaffRequestBody(int staffID) {
            this.staffID = staffID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeeklyDetailsForAStaffResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeeklyDetailsForAStaffResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffResponseBody Body;
        
        public GetWeeklyDetailsForAStaffResponse() {
        }
        
        public GetWeeklyDetailsForAStaffResponse(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeeklyDetailsForAStaffResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetWeeklyDetailsForAStaffResult;
        
        public GetWeeklyDetailsForAStaffResponseBody() {
        }
        
        public GetWeeklyDetailsForAStaffResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetWeeklyDetailsForAStaffResult) {
            this.GetWeeklyDetailsForAStaffResult = GetWeeklyDetailsForAStaffResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDailyDetailsForAStoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDailyDetailsForAStore", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreRequestBody Body;
        
        public GetDailyDetailsForAStoreRequest() {
        }
        
        public GetDailyDetailsForAStoreRequest(ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDailyDetailsForAStoreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int storeID;
        
        public GetDailyDetailsForAStoreRequestBody() {
        }
        
        public GetDailyDetailsForAStoreRequestBody(int storeID) {
            this.storeID = storeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDailyDetailsForAStoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDailyDetailsForAStoreResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreResponseBody Body;
        
        public GetDailyDetailsForAStoreResponse() {
        }
        
        public GetDailyDetailsForAStoreResponse(ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDailyDetailsForAStoreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetDailyDetailsForAStoreResult;
        
        public GetDailyDetailsForAStoreResponseBody() {
        }
        
        public GetDailyDetailsForAStoreResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetDailyDetailsForAStoreResult) {
            this.GetDailyDetailsForAStoreResult = GetDailyDetailsForAStoreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeeklyDetailsForAStoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeeklyDetailsForAStore", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreRequestBody Body;
        
        public GetWeeklyDetailsForAStoreRequest() {
        }
        
        public GetWeeklyDetailsForAStoreRequest(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeeklyDetailsForAStoreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int storeID;
        
        public GetWeeklyDetailsForAStoreRequestBody() {
        }
        
        public GetWeeklyDetailsForAStoreRequestBody(int storeID) {
            this.storeID = storeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWeeklyDetailsForAStoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWeeklyDetailsForAStoreResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreResponseBody Body;
        
        public GetWeeklyDetailsForAStoreResponse() {
        }
        
        public GetWeeklyDetailsForAStoreResponse(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWeeklyDetailsForAStoreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetWeeklyDetailsForAStoreResult;
        
        public GetWeeklyDetailsForAStoreResponseBody() {
        }
        
        public GetWeeklyDetailsForAStoreResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetWeeklyDetailsForAStoreResult) {
            this.GetWeeklyDetailsForAStoreResult = GetWeeklyDetailsForAStoreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ABCosmetic_app.OrderDetailService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ABCosmetic_app.OrderDetailService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="All", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.AllRequestBody Body;
        
        public AllRequest() {
        }
        
        public AllRequest(ABCosmetic_app.OrderDetailService.AllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllRequestBody {
        
        public AllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.AllResponseBody Body;
        
        public AllResponse() {
        }
        
        public AllResponse(ABCosmetic_app.OrderDetailService.AllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> AllResult;
        
        public AllResponseBody() {
        }
        
        public AllResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> AllResult) {
            this.AllResult = AllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByID", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.GetByIDRequestBody Body;
        
        public GetByIDRequest() {
        }
        
        public GetByIDRequest(ABCosmetic_app.OrderDetailService.GetByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetByIDRequestBody() {
        }
        
        public GetByIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.GetByIDResponseBody Body;
        
        public GetByIDResponse() {
        }
        
        public GetByIDResponse(ABCosmetic_app.OrderDetailService.GetByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ABCosmetic_app.OrderDetailService.OrderDetail GetByIDResult;
        
        public GetByIDResponseBody() {
        }
        
        public GetByIDResponseBody(ABCosmetic_app.OrderDetailService.OrderDetail GetByIDResult) {
            this.GetByIDResult = GetByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByName", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.SearchByNameRequestBody Body;
        
        public SearchByNameRequest() {
        }
        
        public SearchByNameRequest(ABCosmetic_app.OrderDetailService.SearchByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        public SearchByNameRequestBody() {
        }
        
        public SearchByNameRequestBody(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ABCosmetic_app.OrderDetailService.SearchByNameResponseBody Body;
        
        public SearchByNameResponse() {
        }
        
        public SearchByNameResponse(ABCosmetic_app.OrderDetailService.SearchByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> SearchByNameResult;
        
        public SearchByNameResponseBody() {
        }
        
        public SearchByNameResponseBody(System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> SearchByNameResult) {
            this.SearchByNameResult = SearchByNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderDetailServiceSoapChannel : ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderDetailServiceSoapClient : System.ServiceModel.ClientBase<ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap>, ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap {
        
        public OrderDetailServiceSoapClient() {
        }
        
        public OrderDetailServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderDetailServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderDetailServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderDetailServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderDetailService.AddNewResponse ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.AddNew(ABCosmetic_app.OrderDetailService.AddNewRequest request) {
            return base.Channel.AddNew(request);
        }
        
        public ABCosmetic_app.OrderDetailService.OrderDetail AddNew(int orderID, int productID, int quantity) {
            ABCosmetic_app.OrderDetailService.AddNewRequest inValue = new ABCosmetic_app.OrderDetailService.AddNewRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.AddNewRequestBody();
            inValue.Body.orderID = orderID;
            inValue.Body.productID = productID;
            inValue.Body.quantity = quantity;
            ABCosmetic_app.OrderDetailService.AddNewResponse retVal = ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).AddNew(inValue);
            return retVal.Body.AddNewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.AddNewResponse> ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.AddNewAsync(ABCosmetic_app.OrderDetailService.AddNewRequest request) {
            return base.Channel.AddNewAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.AddNewResponse> AddNewAsync(int orderID, int productID, int quantity) {
            ABCosmetic_app.OrderDetailService.AddNewRequest inValue = new ABCosmetic_app.OrderDetailService.AddNewRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.AddNewRequestBody();
            inValue.Body.orderID = orderID;
            inValue.Body.productID = productID;
            inValue.Body.quantity = quantity;
            return ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).AddNewAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDResponse ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.GetDetailsByOrderID(ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDRequest request) {
            return base.Channel.GetDetailsByOrderID(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetDetailsByOrderID(int id) {
            ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDRequest inValue = new ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDRequestBody();
            inValue.Body.id = id;
            ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDResponse retVal = ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).GetDetailsByOrderID(inValue);
            return retVal.Body.GetDetailsByOrderIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDResponse> ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.GetDetailsByOrderIDAsync(ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDRequest request) {
            return base.Channel.GetDetailsByOrderIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDResponse> GetDetailsByOrderIDAsync(int id) {
            ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDRequest inValue = new ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.GetDetailsByOrderIDRequestBody();
            inValue.Body.id = id;
            return ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).GetDetailsByOrderIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderDetailService.GetDailyDetailsResponse ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.GetDailyDetails(ABCosmetic_app.OrderDetailService.GetDailyDetailsRequest request) {
            return base.Channel.GetDailyDetails(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetDailyDetails() {
            ABCosmetic_app.OrderDetailService.GetDailyDetailsRequest inValue = new ABCosmetic_app.OrderDetailService.GetDailyDetailsRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.GetDailyDetailsRequestBody();
            ABCosmetic_app.OrderDetailService.GetDailyDetailsResponse retVal = ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).GetDailyDetails(inValue);
            return retVal.Body.GetDailyDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetDailyDetailsResponse> ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.GetDailyDetailsAsync(ABCosmetic_app.OrderDetailService.GetDailyDetailsRequest request) {
            return base.Channel.GetDailyDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetDailyDetailsResponse> GetDailyDetailsAsync() {
            ABCosmetic_app.OrderDetailService.GetDailyDetailsRequest inValue = new ABCosmetic_app.OrderDetailService.GetDailyDetailsRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.GetDailyDetailsRequestBody();
            return ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).GetDailyDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderDetailService.GetWeeklyDetailsResponse ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.GetWeeklyDetails(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsRequest request) {
            return base.Channel.GetWeeklyDetails(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetWeeklyDetails() {
            ABCosmetic_app.OrderDetailService.GetWeeklyDetailsRequest inValue = new ABCosmetic_app.OrderDetailService.GetWeeklyDetailsRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.GetWeeklyDetailsRequestBody();
            ABCosmetic_app.OrderDetailService.GetWeeklyDetailsResponse retVal = ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).GetWeeklyDetails(inValue);
            return retVal.Body.GetWeeklyDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetWeeklyDetailsResponse> ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.GetWeeklyDetailsAsync(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsRequest request) {
            return base.Channel.GetWeeklyDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetWeeklyDetailsResponse> GetWeeklyDetailsAsync() {
            ABCosmetic_app.OrderDetailService.GetWeeklyDetailsRequest inValue = new ABCosmetic_app.OrderDetailService.GetWeeklyDetailsRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.GetWeeklyDetailsRequestBody();
            return ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).GetWeeklyDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffResponse ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.GetDailyDetailsForAStaff(ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffRequest request) {
            return base.Channel.GetDailyDetailsForAStaff(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetDailyDetailsForAStaff(int staffID) {
            ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffRequest inValue = new ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffRequestBody();
            inValue.Body.staffID = staffID;
            ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffResponse retVal = ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).GetDailyDetailsForAStaff(inValue);
            return retVal.Body.GetDailyDetailsForAStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffResponse> ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.GetDailyDetailsForAStaffAsync(ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffRequest request) {
            return base.Channel.GetDailyDetailsForAStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffResponse> GetDailyDetailsForAStaffAsync(int staffID) {
            ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffRequest inValue = new ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStaffRequestBody();
            inValue.Body.staffID = staffID;
            return ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).GetDailyDetailsForAStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffResponse ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.GetWeeklyDetailsForAStaff(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffRequest request) {
            return base.Channel.GetWeeklyDetailsForAStaff(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetWeeklyDetailsForAStaff(int staffID) {
            ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffRequest inValue = new ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffRequestBody();
            inValue.Body.staffID = staffID;
            ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffResponse retVal = ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).GetWeeklyDetailsForAStaff(inValue);
            return retVal.Body.GetWeeklyDetailsForAStaffResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffResponse> ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.GetWeeklyDetailsForAStaffAsync(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffRequest request) {
            return base.Channel.GetWeeklyDetailsForAStaffAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffResponse> GetWeeklyDetailsForAStaffAsync(int staffID) {
            ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffRequest inValue = new ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStaffRequestBody();
            inValue.Body.staffID = staffID;
            return ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).GetWeeklyDetailsForAStaffAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreResponse ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.GetDailyDetailsForAStore(ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreRequest request) {
            return base.Channel.GetDailyDetailsForAStore(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetDailyDetailsForAStore(int storeID) {
            ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreRequest inValue = new ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreRequestBody();
            inValue.Body.storeID = storeID;
            ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreResponse retVal = ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).GetDailyDetailsForAStore(inValue);
            return retVal.Body.GetDailyDetailsForAStoreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreResponse> ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.GetDailyDetailsForAStoreAsync(ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreRequest request) {
            return base.Channel.GetDailyDetailsForAStoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreResponse> GetDailyDetailsForAStoreAsync(int storeID) {
            ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreRequest inValue = new ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.GetDailyDetailsForAStoreRequestBody();
            inValue.Body.storeID = storeID;
            return ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).GetDailyDetailsForAStoreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreResponse ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.GetWeeklyDetailsForAStore(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreRequest request) {
            return base.Channel.GetWeeklyDetailsForAStore(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> GetWeeklyDetailsForAStore(int storeID) {
            ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreRequest inValue = new ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreRequestBody();
            inValue.Body.storeID = storeID;
            ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreResponse retVal = ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).GetWeeklyDetailsForAStore(inValue);
            return retVal.Body.GetWeeklyDetailsForAStoreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreResponse> ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.GetWeeklyDetailsForAStoreAsync(ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreRequest request) {
            return base.Channel.GetWeeklyDetailsForAStoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreResponse> GetWeeklyDetailsForAStoreAsync(int storeID) {
            ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreRequest inValue = new ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.GetWeeklyDetailsForAStoreRequestBody();
            inValue.Body.storeID = storeID;
            return ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).GetWeeklyDetailsForAStoreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderDetailService.HelloWorldResponse ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.HelloWorld(ABCosmetic_app.OrderDetailService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ABCosmetic_app.OrderDetailService.HelloWorldRequest inValue = new ABCosmetic_app.OrderDetailService.HelloWorldRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.HelloWorldRequestBody();
            ABCosmetic_app.OrderDetailService.HelloWorldResponse retVal = ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.HelloWorldResponse> ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.HelloWorldAsync(ABCosmetic_app.OrderDetailService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.HelloWorldResponse> HelloWorldAsync() {
            ABCosmetic_app.OrderDetailService.HelloWorldRequest inValue = new ABCosmetic_app.OrderDetailService.HelloWorldRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.HelloWorldRequestBody();
            return ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderDetailService.AllResponse ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.All(ABCosmetic_app.OrderDetailService.AllRequest request) {
            return base.Channel.All(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> All() {
            ABCosmetic_app.OrderDetailService.AllRequest inValue = new ABCosmetic_app.OrderDetailService.AllRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.AllRequestBody();
            ABCosmetic_app.OrderDetailService.AllResponse retVal = ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).All(inValue);
            return retVal.Body.AllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.AllResponse> ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.AllAsync(ABCosmetic_app.OrderDetailService.AllRequest request) {
            return base.Channel.AllAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.AllResponse> AllAsync() {
            ABCosmetic_app.OrderDetailService.AllRequest inValue = new ABCosmetic_app.OrderDetailService.AllRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.AllRequestBody();
            return ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).AllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderDetailService.GetByIDResponse ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.GetByID(ABCosmetic_app.OrderDetailService.GetByIDRequest request) {
            return base.Channel.GetByID(request);
        }
        
        public ABCosmetic_app.OrderDetailService.OrderDetail GetByID(int id) {
            ABCosmetic_app.OrderDetailService.GetByIDRequest inValue = new ABCosmetic_app.OrderDetailService.GetByIDRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.GetByIDRequestBody();
            inValue.Body.id = id;
            ABCosmetic_app.OrderDetailService.GetByIDResponse retVal = ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).GetByID(inValue);
            return retVal.Body.GetByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetByIDResponse> ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.GetByIDAsync(ABCosmetic_app.OrderDetailService.GetByIDRequest request) {
            return base.Channel.GetByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.GetByIDResponse> GetByIDAsync(int id) {
            ABCosmetic_app.OrderDetailService.GetByIDRequest inValue = new ABCosmetic_app.OrderDetailService.GetByIDRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.GetByIDRequestBody();
            inValue.Body.id = id;
            return ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).GetByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCosmetic_app.OrderDetailService.SearchByNameResponse ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.SearchByName(ABCosmetic_app.OrderDetailService.SearchByNameRequest request) {
            return base.Channel.SearchByName(request);
        }
        
        public System.Collections.Generic.List<ABCosmetic_app.OrderDetailService.OrderDetail> SearchByName(string text) {
            ABCosmetic_app.OrderDetailService.SearchByNameRequest inValue = new ABCosmetic_app.OrderDetailService.SearchByNameRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.SearchByNameRequestBody();
            inValue.Body.text = text;
            ABCosmetic_app.OrderDetailService.SearchByNameResponse retVal = ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).SearchByName(inValue);
            return retVal.Body.SearchByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.SearchByNameResponse> ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap.SearchByNameAsync(ABCosmetic_app.OrderDetailService.SearchByNameRequest request) {
            return base.Channel.SearchByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCosmetic_app.OrderDetailService.SearchByNameResponse> SearchByNameAsync(string text) {
            ABCosmetic_app.OrderDetailService.SearchByNameRequest inValue = new ABCosmetic_app.OrderDetailService.SearchByNameRequest();
            inValue.Body = new ABCosmetic_app.OrderDetailService.SearchByNameRequestBody();
            inValue.Body.text = text;
            return ((ABCosmetic_app.OrderDetailService.OrderDetailServiceSoap)(this)).SearchByNameAsync(inValue);
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
